const emoticons = [
  { 'id': 'EmoticonData_AngelicSupportMastery', 'image': '/i/emoticon/T_AtlasPray-512x512.png' },
  { 'id': 'EmoticonData_AngelicSupportMasteryAnimated', 'image': '/i/emoticon/T_AtlasSigh-512x512.webp' },
  { 'id': 'EmoticonData_ChaoticRocketeerMastery', 'image': '/i/emoticon/T_LunaGoodJob-512x512.png' },
  { 'id': 'EmoticonData_ChaoticRocketeerMasteryAnimated', 'image': '/i/emoticon/T_LunaCalculating-512x512.webp' },
  { 'id': 'EmoticonData_CleverSummonerMastery', 'image': '/i/emoticon/T_JunoBlankStare-512x512.png' },
  { 'id': 'EmoticonData_CleverSummonerMasteryAnimated', 'image': '/i/emoticon/T_JunoShake-512x512.webp' },
  { 'id': 'EmoticonData_EDMOniMastery', 'image': '/i/emoticon/T_OctaviaShrug-512x512.png' },
  { 'id': 'EmoticonData_EDMOniMasteryAnimated', 'image': '/i/emoticon/T_OactaviaYawn-512x512.webp' },
  { 'id': 'EmoticonData_EmpoweringEnchanterMastery', 'image': '/i/emoticon/T_EraShy-512x512.png' },
  { 'id': 'EmoticonData_EmpoweringEnchanterMasteryAnimated', 'image': '/i/emoticon/T_EraThisIsFine-512x512.webp' },
  { 'id': 'EmoticonData_FlashySwordsmanMastery', 'image': '/i/emoticon/T_ZentaroPause-512x512.png' },
  { 'id': 'EmoticonData_FlashySwordsmanMasteryAnimated', 'image': '/i/emoticon/T_ZentaroLaugh-512x512.webp' },
  { 'id': 'EmoticonData_FlexibleBrawlerMastery', 'image': '/i/emoticon/T_JulietteSuccess-512x512.png' },
  { 'id': 'EmoticonData_FlexibleBrawlerMasteryAnimated', 'image': '/i/emoticon/T_JulietteDetermined-512x512.webp' },
  { 'id': 'EmoticonData_HulkingBeastMastery', 'image': '/i/emoticon/T_XFleX-512x512.png' },
  { 'id': 'EmoticonData_HulkingBeastMasteryAnimated', 'image': '/i/emoticon/T_XMenace-512x512.webp' },
  { 'id': 'EmoticonData_MagicalPlaymakerMastery', 'image': '/i/emoticon/T_AimiLaser-512x512.png' },
  { 'id': 'EmoticonData_MagicalPlaymakerMasteryAnimated', 'image': '/i/emoticon/T_AimiKeyboard-512x512.webp' },
  { 'id': 'EmoticonData_ManipulatingMastermindMastery', 'image': '/i/emoticon/T_RuneCreepy-512x512.png' },
  { 'id': 'EmoticonData_ManipulatingMastermindMasteryAnimated', 'image': '/i/emoticon/T_RuneSurprised-512x512.webp' },
  { 'id': 'EmoticonData_NimbleBlasterMastery', 'image': '/i/emoticon/T_DrekarThink-512x512.png' },
  { 'id': 'EmoticonData_NimbleBlasterMasteryAnimated', 'image': '/i/emoticon/T_DrekarMadge-512x512.webp' },
  { 'id': 'EmoticonData_RockOniMastery', 'image': '/i/emoticon/T_RockOniBleh-512x512.png' },
  { 'id': 'EmoticonData_RockOniMasteryAnimated', 'image': '/i/emoticon/T_VyceRockOn-512x512.webp' },
  { 'id': 'EmoticonData_ShieldUserMastery', 'image': '/i/emoticon/T_AsherSus-512x512.png' },
  { 'id': 'EmoticonData_ShieldUserMasteryAnimated', 'image': '/i/emoticon/T_AsherYikes-512x512.webp' },
  { 'id': 'EmoticonData_SpeedySkirmisherMastery', 'image': '/i/emoticon/T_KaiShrug-512x512.png' },
  { 'id': 'EmoticonData_SpeedySkirmisherMasteryAnimated', 'image': '/i/emoticon/T_KaiBurn-512x512.webp' },
  { 'id': 'EmoticonData_StalwartProtectorMastery', 'image': '/i/emoticon/T_DubuOmega-512x512.png' },
  { 'id': 'EmoticonData_StalwartProtectorMasteryAnimated', 'image': '/i/emoticon/T_DubuLetsGo-512x512.webp' },
  { 'id': 'EmoticonData_TempoSniperMastery', 'image': '/i/emoticon/T_EstelleRose-512x512.png' },
  { 'id': 'EmoticonData_TempoSniperMasteryAnimated', 'image': '/i/emoticon/T_EstelleKiss-512x512.webp' },
  { 'id': 'EmoticonData_WhipFighterMastery', 'image': '/i/emoticon/T_RasmusAngry-512x512.png' },
  { 'id': 'EmoticonData_WhipFighterMasteryAnimated', 'image': '/i/emoticon/T_RasmusShocked-512x512.webp' },
  { 'id': 'EmoticonData_AimiCry', 'image': '/i/emoticon/T_AimiCry-png'},
  { 'id': 'EmoticonData_AimiNoted', 'image': '/i/emoticon/T_AimiNoted-512x512.webp'},
  { 'id': 'EmoticonData_AimiSweat', 'image': '/i/emoticon/T_AimiSweat-512x512.png'},
  { 'id': 'EmoticonData_AsherPog', 'image': '/i/emoticon/T_AsherPog-512x512.png'},
  { 'id': 'EmoticonData_AtlasThink', 'image': '/i/emoticon/T_AtlasThink-512x512.png'},
  { 'id': 'EmoticonData_AtlasThumbsUp', 'image': '/i/emoticon/T_AtlasNice-512x512.png'},
  { 'id': 'EmoticonData_DrekarBusiness', 'image': '/i/emoticon/T_DrekarBusiness-512x512.png'},
  { 'id': 'EmoticonData_EraIsThis', 'image': '/i/emoticon/T_EraIsThis-512x512.png'},
  { 'id': 'EmoticonData_EraRainDrop', 'image': '/i/emoticon/T_EraRaindropSad-512x512.png'},
  { 'id': 'EmoticonData_JulietteCopium', 'image': '/i/emoticon/T_JulietteCopium-512x512.png'},
  { 'id': 'EmoticonData_LunaCry', 'image': '/i/emoticon/T_LunaCry-512x512.png'},
  { 'id': 'EmoticonData_LunaGlasses', 'image': '/i/emoticon/T_LunaGlasses-512x512.png'},
  { 'id': 'EmoticonData_LunaWizard', 'image': '/i/emoticon/T_LunaWizardOrb-512x512.png'},
  { 'id': 'EmoticonData_RasmusPray', 'image': '/i/emoticon/T_RasmusPray-512x512.png'},
  { 'id': 'EmoticonData_RuneClone', 'image': '/i/emoticon/T_RuneClone-512x512.png'},
  { 'id': 'EmoticonData_RuneYouAreMe', 'image': '/i/emoticon/T_RuneYou-512x512.png'},
  { 'id': 'EmoticonData_XGigachad', 'image': '/i/emoticon/T_XGigaChad-512x512.png'},
  { 'id': 'EmoticonData_ZentaroDeadge', 'image': '/i/emoticon/T_ZentaroDeadge-512x512.png'},
  { 'id': 'EmoticonData_AiMiCatSalad', 'image': '/i/emoticon/T_AiMiCatSalad-512x512.png'},
  { 'id': 'EmoticonData_AiMiFree', 'image': '/i/emoticon/T_AiMiFree-512x512.png'},
  { 'id': 'EmoticonData_AiMiNom', 'image': '/i/emoticon/T_AiMiNOM-512x512.png'},
  { 'id': 'EmoticonData_AiMiPat', 'image': '/i/emoticon/T_AiMiPat-512x512.png'},
  { 'id': 'EmoticonData_AiMiShocked', 'image': '/i/emoticon/T_AiMiShock-512x512.png'},
  { 'id': 'EmoticonData_AiMiSmug', 'image': '/i/emoticon/T_AiMiSmug-512x512.png'},
  { 'id': 'EmoticonData_AsherCheer', 'image': '/i/emoticon/T_AsherCheer-512x512.png'},
  { 'id': 'EmoticonData_AsherDisgust', 'image': '/i/emoticon/T_AsherDisgust-512x512.png'},
  { 'id': 'EmoticonData_AsherPoint', 'image': '/i/emoticon/T_AsherPoint-512x512.png'},
  { 'id': 'EmoticonData_BlobBlushing', 'image': '/i/emoticon/T_Emoticon_BlushingBlob-512x512.png'},
  { 'id': 'EmoticonData_BlobboCheer', 'image': '/i/emoticon/T_BlobboCheer-512x512.png'},
  { 'id': 'EmoticonData_BlobboLove', 'image': '/i/emoticon/T_BlobboLove-512x512.png'},
  { 'id': 'EmoticonData_BlobboParty', 'image': '/i/emoticon/T_BlobboParty-512x512.png'},
  { 'id': 'EmoticonData_BlobConfused', 'image': '/i/emoticon/T_Emoticon_ConfusedBlob-512x512.png'},
  { 'id': 'EmoticonData_BlobHappy', 'image': '/i/emoticon/T_Emoticon_HappyBlob-512x512.png'},
  { 'id': 'EmoticonData_BlobMad', 'image': '/i/emoticon/T_Emoticon_MadBlob-512x512.png'},
  { 'id': 'EmoticonData_BlobSad', 'image': '/i/emoticon/T_Emoticon_SadBlob-512x512.png'},
  { 'id': 'EmoticonData_BPS1Badge1', 'image': '/i/emoticon/T_Emoticon_Season1BadgeTier3-512x512.png'},
  { 'id': 'EmoticonData_Challenger', 'image': '/i/emoticon/T_UI_RankedEmblem_Master_Low.T_UI_RankedEmblem_Master_Low'},
  { 'id': 'EmoticonData_DefaultThumbsUp', 'image': '/i/emoticon/T_Emoticon_ThumbsUp-512x512.png'},
  { 'id': 'EmoticonData_Diamond', 'image': '/i/emoticon/T_UI_RankedEmblem_Diamond_Low.T_UI_RankedEmblem_Diamond_Low'},
  { 'id': 'EmoticonData_DJAtlas', 'image': '/i/emoticon/T_DJAtlas-512x512.png'},
  { 'id': 'EmoticonData_DrekarDetective', 'image': '/i/emoticon/T_DrexWhat-512x512.png'},
  { 'id': 'EmoticonData_DrekarSpeechless', 'image': '/i/emoticon/T_DrexPog.T_DrexPog'},
  { 'id': 'EmoticonData_DubuBop', 'image': '/i/emoticon/T_DubuNOM.T_DubuNOM'},
  { 'id': 'EmoticonData_DubuCurious', 'image': '/i/emoticon/T_DubuNyo-512x512.png'},
  { 'id': 'EmoticonData_DubuOne', 'image': '/i/emoticon/T_DubuOne-512x512.png'},
  { 'id': 'EmoticonData_DubuPanicked', 'image': '/i/emoticon/T_DubuConcern-512x512.png'},
  { 'id': 'EmoticonData_DubuShocked', 'image': '/i/emoticon/T_DubuShocked-512x512.png'},
  { 'id': 'EmoticonData_EraUwu', 'image': '/i/emoticon/T_EraUwu-512x512.png'},
  { 'id': 'EmoticonData_EstelleFacepalm', 'image': '/i/emoticon/T_EstelleFacepalm-512x512.png'},
  { 'id': 'EmoticonData_EstelleGloat', 'image': '/i/emoticon/T_EstelleOho-512x512.png'},
  { 'id': 'EmoticonData_EternalFlameDubu', 'image': '/i/emoticon/T_Emoticon_EternalFlameDubu-512x512.png'},
  { 'id': 'EmoticonData_Founder', 'image': 'OdysseyProfileLogo_128.OdysseyProfileLogo_128'},
  { 'id': 'EmoticonData_Gold', 'image': '/i/emoticon/T_UI_RankedEmblem_Gold_Low.T_UI_RankedEmblem_Gold_Low'},
  { 'id': 'EmoticonData_Halloween_Duboo', 'image': '/i/emoticon/T_Duboo-512x512.png'},
  { 'id': 'EmoticonData_Halloween_Era_Coffin', 'image': '/i/emoticon/T_EraDeadge-512x512.png'},
  { 'id': 'EmoticonData_Halloween_Estelle_Nurse', 'image': '/i/emoticon/T_EstelleHypers-512x512.png'},
  { 'id': 'EmoticonData_Halloween_Juno_Clown', 'image': '/i/emoticon/T_JunoClown-512x512.png'},
  { 'id': 'EmoticonData_Halloween_XWerewolf', 'image': '/i/emoticon/T_XWerewolf-512x512.png'},
  { 'id': 'EmoticonData_HyperX', 'image': '/i/emoticon/T_HyperX-512x512.png'},
  { 'id': 'EmoticonData_IdolAimiHeart', 'image': '/i/emoticon/T_IdolAimiHeart-512x512.png'},
  { 'id': 'EmoticonData_JulietteComfy', 'image': '/i/emoticon/T_JulietteComfy-512x512.png'},
  { 'id': 'EmoticonData_JulietteCool', 'image': '/i/emoticon/T_JulietteEz-512x512.png'},
  { 'id': 'EmoticonData_JulietteDefeated', 'image': '/i/emoticon/T_JulietteCryge-512x512.png'},
  { 'id': 'EmoticonData_JulietteHeart', 'image': '/i/emoticon/T_JulietteHeart-512x512.png'},
  { 'id': 'EmoticonData_JulietteLightsOut', 'image': '/i/emoticon/T_Emoticon_LightsOut-512x512.png'},
  { 'id': 'EmoticonData_JuliettePunch', 'image': '/i/emoticon/T_JuliettePunch-512x512.png'},
  { 'id': 'EmoticonData_JulietteRave', 'image': '/i/emoticon/T_JulietteRave-512x512.png'},
  { 'id': 'EmoticonData_JulietteThumbsUp', 'image': '/i/emoticon/T_JulietteThumbsUp-512x512.png'},
  { 'id': 'EmoticonData_JulietteVibe', 'image': '/i/emoticon/T_JulietteVibe-512x512.png'},
  { 'id': 'EmoticonData_JunoBop', 'image': '/i/emoticon/T_BigBopJuno-512x512.png'},
  { 'id': 'EmoticonData_JunoCute', 'image': '/i/emoticon/T_JunoHappy-512x512.png'},
  { 'id': 'EmoticonData_JunoDevious', 'image': '/i/emoticon/T_JunoHype-512x512.png'},
  { 'id': 'EmoticonData_JunoFight', 'image': '/i/emoticon/T_JunoFight-512x512.png'},
  { 'id': 'EmoticonData_JunoGawk', 'image': '/i/emoticon/T_JunoZoom-512x512.png'},
  { 'id': 'EmoticonData_JunoGiggle', 'image': '/i/emoticon/T_JunoLul-512x512.png'},
  { 'id': 'EmoticonData_JunoShy', 'image': '/i/emoticon/T_JunoShy-512x512.png'},
  { 'id': 'EmoticonData_JunoSleep', 'image': '/i/emoticon/T_JunoSleep-512x512.png'},
  { 'id': 'EmoticonData_JunoSnackTime', 'image': '/i/emoticon/T_JunoPopcorn-512x512.png'},
  { 'id': 'EmoticonData_JunoStarry', 'image': '/i/emoticon/T_JunoWOW.T_JunoWOW'},
  { 'id': 'EmoticonData_KaiGlamour', 'image': '/i/emoticon/T_KaiSmirk-512x512.png'},
  { 'id': 'EmoticonData_KaiShambles', 'image': '/i/emoticon/T_KaiFine-512x512.png'},
  { 'id': 'EmoticonData_LunaPeace', 'image': '/i/emoticon/T_LunaPeace-512x512.png'},
  { 'id': 'EmoticonData_MusicVS_EdmOni1', 'image': '/i/emoticon/T_OactaviaYawn-512x512.png'},
  { 'id': 'EmoticonData_MusicVS_RockOni', 'image': '/i/emoticon/T_GuitarOniBleh-512x512.png'},
  { 'id': 'EmoticonData_Omega', 'image': '/i/emoticon/T_UI_RankedEmblem_Promethean.T_UI_RankedEmblem_Promethean'},
  { 'id': 'EmoticonData_Platinum', 'image': '/i/emoticon/T_UI_RankedEmblem_Platinum_Low.T_UI_RankedEmblem_Platinum_Low'},
  { 'id': 'EmoticonData_RasmusAngry', 'image': '/i/emoticon/T_RasmusAngry-512x512.png'},
  { 'id': 'EmoticonData_RasmusShocked', 'image': '/i/emoticon/T_RasmusShocked-512x512.png'},
  { 'id': 'EmoticonData_RuneDespair', 'image': '/i/emoticon/T_RuneDespair-512x512.png'},
  { 'id': 'EmoticonData_RunePoor', 'image': '/i/emoticon/T_RunePoor-512x512.png'},
  { 'id': 'EmoticonData_RuneV', 'image': '/i/emoticon/T_RuneV-512x512.png'},
  { 'id': 'EmoticonData_SoniiPepega', 'image': '/i/emoticon/T_SoniiPepega-512x512.png'},
  { 'id': 'EmoticonData_SoniiSalute', 'image': '/i/emoticon/T_SoniiSalute-512x512.png'},
  { 'id': 'EmoticonData_STARLEAGUE', 'image': '/i/emoticon/T_STARLEAGUE-512x512.png'},
  { 'id': 'EmoticonData_TeamEDM', 'image': '/i/emoticon/T_TeamEDM-512x512.png'},
  { 'id': 'EmoticonData_TeamRock', 'image': '/i/emoticon/T_TeamRock-512x512.png'},
  { 'id': 'EmoticonData_TeaTimeDubu', 'image': '/i/emoticon/T_TeaTimeDubu-512x512.png'},
  { 'id': 'EmoticonData_TeaTimeFini', 'image': '/i/emoticon/T_TeaTimeFini-512x512.png'},
  { 'id': 'EmoticonData_TeaTimeMatcha', 'image': '/i/emoticon/T_TeaTimeMatcha-512x512.png'},
  { 'id': 'EmoticonData_TeaTimeMilk', 'image': '/i/emoticon/T_TeaTimeMilk-512x512.png'},
  { 'id': 'EmoticonData_TeaTimePumpkin', 'image': '/i/emoticon/T_TeaTimePumpkin-512x512.png'},
  { 'id': 'EmoticonData_TeaTimeTaro', 'image': '/i/emoticon/T_TeaTimeTaro-512x512.png'},
  { 'id': 'EmoticonData_T_Emoticon_WumpusFive', 'image': '/i/emoticon/T_Emoticon_WumpusFive-512x512.png'},
  { 'id': 'EmoticonData_T_Emoticon_WumpusGoalie', 'image': '/i/emoticon/T_Emoticon_WumpusGoalie-512x512.png'},
  { 'id': 'EmoticonData_T_Emoticon_WumpusStrike', 'image': '/i/emoticon/T_Emoticon_WumpusStrike-512x512.png'},
  { 'id': 'EmoticonData_XRage', 'image': '/i/emoticon/T_XRAGE-512x512.png'}
]

export default emoticons