import Footer from '@/components/molecules/Footer'
import Navbar from '@/components/molecules/Navbar'
import '@/styles/globals.css'
import '@/styles/tweaks.scss'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Strikr | %s',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
