const awakeningRotation = [
  'T_Aerials',
  'T_AmongTitans',
  'T_BuiltDifferent',
  'T_CastToLast',
  'T_Chronoboost',
  'T_DeadEye',
  'T_Demolitionist',
  'T_ExplosiveEntrance',
  'T_ExtraSpecial',
  'T_FightorFlight',
  'T_GlassCannon',
  'T_HeavyImpact',
  'T_HotShot',
  'T_KnifesEdge',
  'T_MissilePropulsion',
  'T_Monumentalist',
  'T_OneTwoPunch',
  'T_PrimeTime',
  'T_PrizeFighter',
  'T_QuickStrike',
  'T_RapidFire',
  'T_RecoveryDrone',
  'T_SiegeMachine',
  'T_SparkofAgility',
  'T_SparkofFocus',
  'T_SparkofLeadership',
  'T_SparkofResilience',
  'T_SparkofStrength',
  'T_SpecializedTraining',
  'T_StaggerSwagger',
  'T_TeamPlayer',
  'T_TimelessCreator',
  'T_TwinDrive',
  'T_Unstoppable',
]

export default awakeningRotation