const awakeningRotation = [
  // 'T_AdrenalineRush',
  'T_Aerials',
  'T_BigFish',
  'T_BuiltDifferent',
  'T_BulkUp',
  'T_CastToLast',
  'T_Chronoboost',
  'T_DeadEye',
  'T_ExtraSpecial',
  'T_GlassCannon',
  'T_HotShot',
  'T_ImpactSpecialist',
  'T_MissilePropulsion',
  'T_Monumentalist',
  // 'T_SparkofStrength',
  'T_OrbDancer',
  'T_OrbPonderer',
  'T_OrbSharer',
  'T_PeakPerformance',
  'T_PrimeTime',
  'T_PrizeFighter',
  // 'T_Unstoppable',
  'T_QuickStrike',
  'T_RapidFire',
  'T_ShockAndAwe',
  // 'T_SparkofAgility',
  // 'T_SparkofFocus',
  // 'T_SparkofResilience',
  'T_StacksOnStacks',
  'T_StaggerSwagger',
  // 'T_Stinger',
  'T_Reverberation',
  'T_SuperSurge',
  'T_Egoist',
  'T_FireUp',
  'T_Catalyst',
  'T_TempoSwings',
  'T_TimelessCreator',
  'T_TwinDrive'
]

export default awakeningRotation