const emoticons = [
  { id: 'EmoticonData_AngelicSupportMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_AtlasPray-512x512.png' },
  { id: 'EmoticonData_AngelicSupportMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_AtlasSigh-512x512.webp' },
  { id: 'EmoticonData_ChaoticRocketeerMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_LunaGoodJob-512x512.png' },
  { id: 'EmoticonData_ChaoticRocketeerMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_LunaCalculating-512x512.webp' },
  { id: 'EmoticonData_CleverSummonerMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_JunoBlankStare-512x512.png' },
  { id: 'EmoticonData_CleverSummonerMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_JunoShake-512x512.webp' },
  { id: 'EmoticonData_EDMOniMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_OctaviaShrug-512x512.png' },
  { id: 'EmoticonData_EDMOniMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_OctaviaYawn-512x512.webp' },
  { id: 'EmoticonData_EmpoweringEnchanterMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_EraShy-512x512.png' },
  { id: 'EmoticonData_EmpoweringEnchanterMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_EraThisIsFine-512x512.webp' },
  { id: 'EmoticonData_FlashySwordsmanMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_ZentaroPause-512x512.png' },
  { id: 'EmoticonData_FlashySwordsmanMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_ZentaroLaugh-512x512.webp' },
  { id: 'EmoticonData_FlexibleBrawlerMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_JulietteSuccess-512x512.png' },
  { id: 'EmoticonData_FlexibleBrawlerMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_JulietteDetermined-512x512.webp' },
  { id: 'EmoticonData_HulkingBeastMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_XFleX-512x512.png' },
  { id: 'EmoticonData_HulkingBeastMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_XMenace-512x512.webp' },
  { id: 'EmoticonData_MagicalPlaymakerMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_AimiLaser-512x512.png' },
  { id: 'EmoticonData_MagicalPlaymakerMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_AimiKeyboard-512x512.webp' },
  { id: 'EmoticonData_ManipulatingMastermindMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_RuneCreepy-512x512.png' },
  { id: 'EmoticonData_ManipulatingMastermindMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_RuneSurprised-512x512.webp' },
  { id: 'EmoticonData_NimbleBlasterMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_DrekarThink-512x512.png' },
  { id: 'EmoticonData_NimbleBlasterMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_DrekarMadge-512x512.webp' },
  { id: 'EmoticonData_RockOniMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_RockOniBleh-512x512.png' },
  { id: 'EmoticonData_RockOniMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_VyceRockOn-512x512.webp' },
  { id: 'EmoticonData_ShieldUserMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_AsherSus-512x512.png' },
  { id: 'EmoticonData_ShieldUserMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_AsherYikes-512x512.webp' },
  { id: 'EmoticonData_SpeedySkirmisherMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_KaiShrug-512x512.png' },
  { id: 'EmoticonData_SpeedySkirmisherMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_KaiBurn-512x512.webp' },
  { id: 'EmoticonData_StalwartProtectorMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_DubuOmega-512x512.png' },
  { id: 'EmoticonData_StalwartProtectorMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_DubuLetsGo-512x512.webp' },
  { id: 'EmoticonData_TempoSniperMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_EstelleRose-512x512.png' },
  { id: 'EmoticonData_TempoSniperMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_EstelleKiss-512x512.webp' },
  { id: 'EmoticonData_WhipFighterMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_RasmusAngry-512x512.png' },
  { id: 'EmoticonData_WhipFighterMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_RasmusShocked-512x512.webp' },
  { id: 'EmoticonData_UmbrellaUserMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_KasanLosinIt.png' },
  { id: 'EmoticonData_UmbrellaUserMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_KasanRain.webp' },
  { id: 'EmoticonData_HealerMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_HealerOk.png' },
  { id: 'EmoticonData_HealerMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_HealerAngry.webp' },
  { id: 'EmoticonData_DrumOniMastery', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_DrumOniWOO.png' },
  { id: 'EmoticonData_DrumOniMasteryAnimated', image: 'http://localhost:3000/i/emoticon/StrikerAffinity/T_OniBongo.webp' },

  { id: 'EmoticonData_Rookie', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Rookie_Low.png'},// Ranks
  { id: 'EmoticonData_Bronze', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Bronze_Low.png'},
  { id: 'EmoticonData_Silver', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Silver_Low.png'},
  { id: 'EmoticonData_Gold', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Gold_Low.png'},
  { id: 'EmoticonData_Platinum', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Platinum_Low.png'},
  { id: 'EmoticonData_Diamond', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Diamond_Low.png'},
  { id: 'EmoticonData_Challenger', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Master_Low.png'},
  { id: 'EmoticonData_Omega', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_Promethean.png'},
  { id: 'EmoticonData_ProLeague', image: 'http://localhost:3000/i/rank/T_UI_RankedEmblem_ProLeague.png'},
  
  { id: 'EmoticonData_DrekarDetective', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_DrexWhat-512x512.png'}, // Beta Season Pass
  { id: 'EmoticonData_DrekarSpeechless', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_DrexPog.png'},
  { id: 'EmoticonData_DubuShocked', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_DubuShocked-512x512.png'},
  { id: 'EmoticonData_EstelleFacepalm', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_EstelleFacepalm-512x512.png'},
  { id: 'EmoticonData_EstelleGloat', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_EstelleOho-512x512.png'},
  { id: 'EmoticonData_JulietteCool', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_JulietteEz-512x512.png'},
  { id: 'EmoticonData_JulietteThumbsUp', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_JulietteThumbsUp-512x512.png'},
  { id: 'EmoticonData_JunoFight', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_JunoFight-512x512.png'},
  { id: 'EmoticonData_JunoSleep', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_JunoSleep-512x512.png'},
  { id: 'EmoticonData_KaiShambles', image: 'http://localhost:3000/i/emoticon/Season0Pass/T_KaiFine-512x512.png'},

  { id: 'EmoticonData_AimiCry', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_AimiCry-png'},// Season 1 Pass
  { id: 'EmoticonData_AimiNoted', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_AimiNoted-512x512.webp'},
  { id: 'EmoticonData_AimiSweat', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_AimiSweat-512x512.webp'},
  { id: 'EmoticonData_AsherPog', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_AsherPog-512x512.png'},
  { id: 'EmoticonData_AtlasThumbsUp', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_AtlasNice-512x512.png'},
  { id: 'EmoticonData_AtlasThink', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_AtlasThink-512x512.png'},
  { id: 'EmoticonData_DrekarBusiness', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_DrekarBusiness-512x512.png'},
  { id: 'EmoticonData_EraIsThis', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_EraIsThis-512x512.png'},
  { id: 'EmoticonData_EraRainDrop', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_EraRaindropSad-512x512.png'},
  { id: 'EmoticonData_JulietteCopium', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_JulietteCopium-512x512.png'},
  { id: 'EmoticonData_LunaCry', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_LunaCry-512x512.png'},
  { id: 'EmoticonData_LunaGlasses', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_LunaGlasses-512x512.png'},
  { id: 'EmoticonData_LunaWizard', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_LunaWizardOrb-512x512.png'},
  { id: 'EmoticonData_RasmusPray', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_RasmusPray-512x512.png'},
  { id: 'EmoticonData_RuneClone', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_RuneClone-512x512.png'},
  { id: 'EmoticonData_RuneYouAreMe', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_RuneYou-512x512.png'},
  { id: 'EmoticonData_XGigachad', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_XGigaChad-512x512.png'},
  { id: 'EmoticonData_ZentaroDeadge', image: 'http://localhost:3000/i/emoticon/Season1Pass/T_ZentaroDeadge-512x512.png'},

  { id: 'EmoticonData_AiMiTank', image: 'https://localhost:3000/i/emoticon/Season2Pass/AiMiTank-512x512.png' }, // Season 2 Pass
  { id: 'EmoticonData_AsherShy', image: 'https://localhost:3000/i/emoticon/Season2Pass/AsherShy-512x512.png' },
  { id: 'EmoticonData_AtlasHeal', image: 'https://localhost:3000/i/emoticon/Season2Pass/AtlasHeal-512x512.png' },
  { id: 'EmoticonData_DrekarBlahBlah', image: 'https://localhost:3000/i/emoticon/Season2Pass/DrekarBlahBlah-512x512.png' },
  { id: 'EmoticonData_DrekarPeace', image: 'https://localhost:3000/i/emoticon/Season2Pass/DrekarPeace-512x512.png' },
  { id: 'EmoticonData_DubuHuh', image: 'https://localhost:3000/i/emoticon/Season2Pass/DubuHuh-512x512.png' },
  { id: 'EmoticonData_DubuIceCream', image: 'https://localhost:3000/i/emoticon/Season2Pass/DubuIceCream-512x512.png' },
  { id: 'EmoticonData_DubuYas', image: 'https://localhost:3000/i/emoticon/Season2Pass/DubuYas-512x512.png' },
  { id: 'EmoticonData_FiniiNo', image: 'https://localhost:3000/i/emoticon/Season2Pass/FiniiNo-512x512.png' },
  { id: 'EmoticonData_FiniiTeehee', image: 'https://localhost:3000/i/emoticon/Season2Pass/FiniiTeehee-512x512.png' },
  { id: 'EmoticonData_JunoSurrender', image: 'https://localhost:3000/i/emoticon/Season2Pass/JunoSurrender-512x512.png' },
  { id: 'EmoticonData_LunaBoom', image: 'https://localhost:3000/i/emoticon/Season2Pass/LunaBoom-512x512.png' },
  { id: 'EmoticonData_LunaRun', image: 'https://localhost:3000/i/emoticon/Season2Pass/LunaRun-512x512.png' },
  { id: 'EmoticonData_OctaviaCheers', image: 'https://localhost:3000/i/emoticon/Season2Pass/OctaviaCheers-512x512.png' },
  { id: 'EmoticonData_OctaviaRun', image: 'https://localhost:3000/i/emoticon/Season2Pass/OctaviaRun-512x512.png' },
  { id: 'EmoticonData_RasmusBusiness', image: 'https://localhost:3000/i/emoticon/Season2Pass/RasmusBusiness-512x512.png' },
  { id: 'EmoticonData_RuneCry', image: 'https://localhost:3000/i/emoticon/Season2Pass/RuneCry-512x512.png' },
  { id: 'EmoticonData_VyceCheers', image: 'https://localhost:3000/i/emoticon/Season2Pass/VyceCheers-512x512.png' },
  { id: 'EmoticonData_VyceSweat', image: 'https://localhost:3000/i/emoticon/Season2Pass/VyceSweat-512x512.png' },
  { id: 'EmoticonData_ZentaroCryMask', image: 'https://localhost:3000/i/emoticon/Season2Pass/ZentaroCryMask-512x512.png' },

  { id: 'EmoticonData_AiMiCatSalad', image: 'http://localhost:3000/i/emoticon/Store/T_AiMiCatSalad-512x512.png'}, // Store
  { id: 'EmoticonData_AiMiFree', image: 'http://localhost:3000/i/emoticon/Store/T_AiMiFree-512x512.png'},
  { id: 'EmoticonData_AiMiNom', image: 'http://localhost:3000/i/emoticon/Store/T_AiMiNOM-512x512.png'},
  { id: 'EmoticonData_AiMiPat', image: 'http://localhost:3000/i/emoticon/Store/T_AiMiPat-512x512.png'},
  { id: 'EmoticonData_AiMiShocked', image: 'http://localhost:3000/i/emoticon/Store/T_AiMiShock-512x512.png'},
  { id: 'EmoticonData_AiMiSmug', image: 'http://localhost:3000/i/emoticon/Store/T_AiMiSmug-512x512.png'},
  { id: 'EmoticonData_AsherCheer', image: 'http://localhost:3000/i/emoticon/Store/T_AsherCheer-512x512.png'},
  { id: 'EmoticonData_AsherDisgust', image: 'http://localhost:3000/i/emoticon/Store/T_AsherDisgust-512x512.png'},
  { id: 'EmoticonData_AsherPoint', image: 'http://localhost:3000/i/emoticon/Store/T_AsherPoint-512x512.png'},
  { id: 'EmoticonData_BlobBlushing', image: 'http://localhost:3000/i/emoticon/Store//T_Emoticon_BlushingBlob-512x512.png'},
  { id: 'EmoticonData_BlobConfused', image: 'http://localhost:3000/i/emoticon/Store/T_Emoticon_ConfusedBlob-512x512.png'},
  { id: 'EmoticonData_BlobHappy', image: 'http://localhost:3000/i/emoticon/Store/T_Emoticon_HappyBlob-512x512.png'},
  { id: 'EmoticonData_BlobMad', image: 'http://localhost:3000/i/emoticon/Store/T_Emoticon_MadBlob-512x512.png'},
  { id: 'EmoticonData_BlobSad', image: 'http://localhost:3000/i/emoticon/Store/T_Emoticon_SadBlob-512x512.png'},
  { id: 'EmoticonData_DrumOniMenace', image: 'http://localhost:3000/i/emoticon/Store/T_DrumOniMenace-512x512.png'},
  { id: 'EmoticonData_DubuCurious', image: 'http://localhost:3000/i/emoticon/Store/T_DubuNyo-512x512.png'},
  { id: 'EmoticonData_DubuPanicked', image: 'http://localhost:3000/i/emoticon/Store/T_DubuConcern-512x512.png'},
  { id: 'EmoticonData_JulietteDefeated', image: 'http://localhost:3000/i/emoticon/Store/T_JulietteCryge-512x512.png'},
  { id: 'EmoticonData_JulietteRave', image: 'http://localhost:3000/i/emoticon/Store/T_JulietteRave-512x512.png'},
  { id: 'EmoticonData_XRage', image: 'http://localhost:3000/i/emoticon/Store/T_XRAGE-512x512.png'},

  { id: 'EmoticonData_BlobboCheer', image: 'http://localhost:3000/i/emoticon/T_BlobboCheer-512x512.png'},
  { id: 'EmoticonData_BlobboLove', image: 'http://localhost:3000/i/emoticon/T_BlobboLove-512x512.png'},
  { id: 'EmoticonData_BlobboParty', image: 'http://localhost:3000/i/emoticon/T_BlobboParty-512x512.png'},
  { id: 'EmoticonData_BPS1Badge1', image: 'http://localhost:3000/i/emoticon/T_Emoticon_Season1BadgeTier3-512x512.png'},
  { id: 'EmoticonData_DefaultThumbsUp', image: 'http://localhost:3000/i/emoticon/T_Emoticon_ThumbsUp-512x512.png'},
  { id: 'EmoticonData_DJAtlas', image: 'http://localhost:3000/i/emoticon/T_DJAtlas-512x512.webp'},
  { id: 'EmoticonData_DubuBop', image: 'http://localhost:3000/i/emoticon/T_DubuNOM.T_DubuNOM'},
  { id: 'EmoticonData_DubuOne', image: 'http://localhost:3000/i/emoticon/T_DubuOne-512x512.png'},
  { id: 'EmoticonData_EraUwu', image: 'http://localhost:3000/i/emoticon/T_EraUwu-512x512.png'},
  { id: 'EmoticonData_EternalFlameDubu', image: 'http://localhost:3000/i/emoticon/T_Emoticon_EternalFlameDubu-512x512.png'},
  { id: 'EmoticonData_Founder', image: 'http://localhost:3000/i/emoticon/OdysseyProfileLogo_128.png'},
  { id: 'EmoticonData_HyperX', image: 'http://localhost:3000/i/emoticon/T_HyperX-512x512.png'},
  { id: 'EmoticonData_IdolAimiHeart', image: 'http://localhost:3000/i/emoticon/T_IdolAimiHeart-512x512.png'},
  { id: 'EmoticonData_JulietteComfy', image: 'http://localhost:3000/i/emoticon/T_JulietteComfy-512x512.png'},
  { id: 'EmoticonData_JulietteHeart', image: 'http://localhost:3000/i/emoticon/T_JulietteHeart-512x512.png'},
  { id: 'EmoticonData_JulietteLightsOut', image: 'http://localhost:3000/i/emoticon/T_Emoticon_LightsOut-512x512.png'},
  { id: 'EmoticonData_JuliettePunch', image: 'http://localhost:3000/i/emoticon/T_JuliettePunch-512x512.png'},
  { id: 'EmoticonData_JulietteVibe', image: 'http://localhost:3000/i/emoticon/T_JulietteVibe-512x512.png'},
  { id: 'EmoticonData_JunoBop', image: 'http://localhost:3000/i/emoticon/T_BigBopJuno-512x512.png'},
  { id: 'EmoticonData_JunoCute', image: 'http://localhost:3000/i/emoticon/T_JunoHappy-512x512.png'},
  { id: 'EmoticonData_JunoDevious', image: 'http://localhost:3000/i/emoticon/T_JunoHype-512x512.png'},
  { id: 'EmoticonData_JunoGawk', image: 'http://localhost:3000/i/emoticon/T_JunoZoom-512x512.png'},
  { id: 'EmoticonData_JunoGiggle', image: 'http://localhost:3000/i/emoticon/T_JunoLul-512x512.png'},
  { id: 'EmoticonData_JunoShy', image: 'http://localhost:3000/i/emoticon/T_JunoShy-512x512.png'},
  { id: 'EmoticonData_JunoSnackTime', image: 'http://localhost:3000/i/emoticon/T_JunoPopcorn-512x512.png'},
  { id: 'EmoticonData_JunoStarry', image: 'http://localhost:3000/i/emoticon/T_JunoWOW.png'},
  { id: 'T_JunoWOW', image: 'http://localhost:3000/i/emoticon/T_JunoWOW.png'},
  { id: 'EmoticonData_KaiGlamour', image: 'http://localhost:3000/i/emoticon/T_KaiSmirk-512x512.png'},
  { id: 'EmoticonData_LunaPeace', image: 'http://localhost:3000/i/emoticon/T_LunaPeace-512x512.png'},
  { id: 'EmoticonData_MusicVS_EdmOni1', image: 'http://localhost:3000/i/emoticon/T_OactaviaYawn-512x512.png'},
  { id: 'EmoticonData_MusicVS_RockOni', image: 'http://localhost:3000/i/emoticon/T_GuitarOniBleh-512x512.png'},
  { id: 'EmoticonData_RasmusAngry', image: 'http://localhost:3000/i/emoticon/T_RasmusAngry-512x512.png'},
  { id: 'EmoticonData_RasmusShocked', image: 'http://localhost:3000/i/emoticon/T_RasmusShocked-512x512.png'},
  { id: 'EmoticonData_RuneDespair', image: 'http://localhost:3000/i/emoticon/T_RuneDespair-512x512.png'},
  { id: 'EmoticonData_RunePoor', image: 'http://localhost:3000/i/emoticon/T_RunePoor-512x512.png'},
  { id: 'EmoticonData_RuneV', image: 'http://localhost:3000/i/emoticon/T_RuneV-512x512.png'},
  { id: 'EmoticonData_STARLEAGUE', image: 'http://localhost:3000/i/emoticon/T_STARLEAGUE-512x512.png'},
  { id: 'EmoticonData_T_Emoticon_WumpusFive', image: 'http://localhost:3000/i/emoticon/T_Emoticon_WumpusFive-512x512.png'},
  { id: 'EmoticonData_T_Emoticon_WumpusGoalie', image: 'http://localhost:3000/i/emoticon/T_Emoticon_WumpusGoalie-512x512.png'},
  { id: 'EmoticonData_T_Emoticon_WumpusStrike', image: 'http://localhost:3000/i/emoticon/T_Emoticon_WumpusStrike-512x512.png'},

  { id: 'EmoticonData_BlobAssexual', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobAssexual-512x512.png'},
  { id: 'EmoticonData_BlobBissexual', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobBissexual-512x512.png'},
  { id: 'EmoticonData_BlobGay', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobGay-512x512.png'},
  { id: 'EmoticonData_BlobLesbian', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobLesbian-512x512.png'},
  { id: 'EmoticonData_BlobPansexual', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobPansexual-512x512.png'},
  { id: 'EmoticonData_BlobTrans', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobTrans-512x512.png'},
  { id: 'EmoticonData_BlobNonbinary', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobNonbinary-512x512.png'},
  { id: 'EmoticonData_BlobPride', image: 'http://localhost:3000/i/emoticon/Pride/T_BlobPride-512x512.png'},

  { id: 'EmoticonData_AtlasDefend', image: 'http://localhost:3000/i/emoticon/T_AtlasDefend-512x512.webp'}, // Community emotes
  { id: 'EmoticonData_AsherTank', image: 'https://omegastrikers.wiki.gg/images/c/c4/Asher_Tank.png' },
  { id: 'EmoticonData_AtlasTank', image: 'https://omegastrikers.wiki.gg/images/f/fe/Atlas_Tank.png' },
  { id: 'EmoticonData_DrekarTank', image: 'https://omegastrikers.wiki.gg/images/7/7f/Drekar_Tank.png' },
  { id: 'EmoticonData_DubuTank', image: 'https://omegastrikers.wiki.gg/images/3/30/Dubu_Tank.png' },
  { id: 'EmoticonData_EraTank', image: 'https://omegastrikers.wiki.gg/images/c/c3/Era_Tank.png' },
  { id: 'EmoticonData_EstelleTank', image: 'https://omegastrikers.wiki.gg/images/d/dc/Estelle_Tank.png' },
  { id: 'EmoticonData_FiniiTank', image: 'https://omegastrikers.wiki.gg/images/3/38/Finii_Tank.png' },
  { id: 'EmoticonData_JulietteTank', image: 'https://omegastrikers.wiki.gg/images/1/14/Juliette_Tank.png' },
  { id: 'EmoticonData_JunoTank', image: 'https://omegastrikers.wiki.gg/images/2/25/Juno_Tank.png' },
  { id: 'EmoticonData_KaiTank', image: 'https://omegastrikers.wiki.gg/images/c/c4/Kai_Tank.png' },
  { id: 'EmoticonData_KazanTank', image: 'https://omegastrikers.wiki.gg/images/3/3b/Kazan_Tank.png' },
  { id: 'EmoticonData_LunaTank', image: 'https://omegastrikers.wiki.gg/images/8/8d/Luna_Tank.png' },
  { id: 'EmoticonData_MakoTank', image: 'https://omegastrikers.wiki.gg/images/e/e0/Mako_Tank.png' },
  { id: 'EmoticonData_NaoTank', image: 'https://omegastrikers.wiki.gg/images/9/98/Nao_Tank.png' },
  { id: 'EmoticonData_OctaviaTank', image: 'https://omegastrikers.wiki.gg/images/6/6c/Octavia_Tank.png' },
  { id: 'EmoticonData_RasmusTank', image: 'https://omegastrikers.wiki.gg/images/d/d6/Rasmus_Tank.png' },
  { id: 'EmoticonData_RuneTank', image: 'https://omegastrikers.wiki.gg/images/6/68/Rune_Tank.png' },
  { id: 'EmoticonData_VyceTank', image: 'https://omegastrikers.wiki.gg/images/7/76/Vyce_Tank.png' },
  { id: 'EmoticonData_XTank', image: 'https://omegastrikers.wiki.gg/images/1/1e/X_Tank.png' },
  { id: 'EmoticonData_ZentaroTank', image: 'https://omegastrikers.wiki.gg/images/7/7d/Zentaro_Tank.png' },
  { id: 'EmoticonData_AiMiJam', image: 'https://omegastrikers.wiki.gg/images/a/a7/AiMiJam.gif' },
  { id: 'EmoticonData_DubuCheer', image: 'https://omegastrikers.wiki.gg/images/8/88/Show_Me_Them_Paws_Emoticon.gif' },
  // { id: 'EmoticonData_DubuCooking', image: '' },
  // { id: 'EmoticonData_SweatingAtlas', image: '' },
  // { id: 'EmoticonData_WiwiSmile', image: '' },

  { id: 'EmoticonData_SoniiPepega', image: 'http://localhost:3000/i/emoticon/T_SoniiPepega-512x512.png'}, // Tourneys
  { id: 'EmoticonData_SoniiSalute', image: 'http://localhost:3000/i/emoticon/T_SoniiSalute-512x512.png'},
  { id: 'EmoticonData_SoniiTrophy', image: 'https://localhost:3000/i/emoticon/T_SoniiTrophy-512x512.png' },
  { id: 'EmoticonData_SADBOIS', image: 'https://localhost:3000/i/emoticon/Community/T_SADBOIS-512x512.png' },
  { id: 'EmoticonData_Colin', image: 'https://omegastrikers.wiki.gg/images/7/7a/Colin_Emoticon.png' },

  { id: 'EmoticonData_Halloween_Duboo', image: 'http://localhost:3000/i/emoticon/T_Duboo-512x512.png'}, // Events
  { id: 'EmoticonData_Halloween_Era_Coffin', image: 'http://localhost:3000/i/emoticon/T_EraDeadge-512x512.png'},
  { id: 'EmoticonData_Halloween_Estelle_Nurse', image: 'http://localhost:3000/i/emoticon/T_EstelleHypers-512x512.png'},
  { id: 'EmoticonData_Halloween_Juno_Clown', image: 'http://localhost:3000/i/emoticon/T_JunoClown-512x512.png'},
  { id: 'EmoticonData_Halloween_XWerewolf', image: 'http://localhost:3000/i/emoticon/T_XWerewolf-512x512.png'},
  { id: 'EmoticonData_TeamEDM', image: 'http://localhost:3000/i/emoticon/T_TeamEDM-512x512.png'},
  { id: 'EmoticonData_TeamRock', image: 'http://localhost:3000/i/emoticon/T_TeamRock-512x512.png'},
  { id: 'EmoticonData_TeaTimeDubu', image: 'http://localhost:3000/i/emoticon/T_TeaTimeDubu-512x512.png'},
  { id: 'EmoticonData_TeaTimeFini', image: 'http://localhost:3000/i/emoticon/T_TeaTimeFini-512x512.png'},
  { id: 'EmoticonData_TeaTimeMatcha', image: 'http://localhost:3000/i/emoticon/T_TeaTimeMatcha-512x512.png'},
  { id: 'EmoticonData_TeaTimeMilk', image: 'http://localhost:3000/i/emoticon/T_TeaTimeMilk-512x512.png'},
  { id: 'EmoticonData_TeaTimePumpkin', image: 'http://localhost:3000/i/emoticon/T_TeaTimePumpkin-512x512.png'},
  { id: 'EmoticonData_TeaTimeTaro', image: 'http://localhost:3000/i/emoticon/T_TeaTimeTaro-512x512.png'},
  { id: 'EmoticonData_SummerAsher', image: 'http://localhost:3000/i/emoticon/T_SummerAsher-512x512.png'},
  { id: 'EmoticonData_SummerDubu', image: 'http://localhost:3000/i/emoticon/T_SummerDubu-512x512.png'},
  { id: 'EmoticonData_SummerEstelle', image: 'http://localhost:3000/i/emoticon/T_SummerEstelle-512x512.png'},
  { id: 'EmoticonData_SummerJuliette', image: 'http://localhost:3000/i/emoticon/T_SummerJuliette-512x512.png'},
  { id: 'EmoticonData_SummerJuno', image: 'http://localhost:3000/i/emoticon/T_SummerJuno-512x512.png'},
  { id: 'EmoticonData_SummerX', image: 'http://localhost:3000/i/emoticon/T_SummerX-512x512.png'},
  { id: 'EmoticonData_ClarionVSEnergyTeam', image: 'https://localhost:3000/i/emoticon/ClarionCorpTeamEnergy-512x512.png' },
  { id: 'EmoticonData_ClarionVSReward', image: 'https://localhost:3000/i/emoticon/ClarionCorpTEventReward-512x512.png' },
  { id: 'EmoticonData_ClarionVSStrengthTeam', image: 'https://localhost:3000/i/emoticon/ClarionCorpTeamStrength-512x512.png' },
  { id: 'EmoticonData_ClarionVSTechTeam', image: 'https://localhost:3000/i/emoticon/ClarionCorpTeamTech-512x512.png' },
  { id: 'EmoticonData_ProLeagueVS', image: 'https://localhost:3000/i/emoticon/T_ProLeague-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSByteBreaker', image: 'https://localhost:3000/i/emoticon/T_TeamBB-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSClarionCorp', image: 'https://localhost:3000/i/emoticon/T_TeamCC-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSDemonDrive', image: 'https://localhost:3000/i/emoticon/T_TeamDD-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSEmberMonarchs', image: 'https://localhost:3000/i/emoticon/T_TeamEM-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSFrostfire', image: 'https://localhost:3000/i/emoticon/T_TeamFrostFire-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSMaelstrom', image: 'https://localhost:3000/i/emoticon/T_TeamMaelstrom-512x512.png' },
  { id: 'EmoticonData_ProLeagueVSSSR', image: 'https://localhost:3000/i/emoticon/T_TeamSSR-512x512.png' },

  { id: 'EmoticonData_5up', image: 'https://omegastrikers.wiki.gg/images/f/ff/5UP_Emoticon.png' }, // creators
  { id: 'EmoticonData_Aethelstan', image: ''},
  { id: 'EmoticonData_Alpharad', image: ''},
  { id: 'EmoticonData_Ariken', image: ''},
  { id: 'EmoticonData_AsmonGold', image: ''},
  { id: 'EmoticonData_AustinFelt', image: ''},
  { id: 'EmoticonData_BeatEmUps', image: ''},
  { id: 'EmoticonData_Blau', image: ''},
  { id: 'EmoticonData_Blau2', image: ''},
  { id: 'EmoticonData_Blau3', image: 'https://omegastrikers.wiki.gg/images/9/9c/Blau3_Emoticon.png' },
  { id: 'EmoticonData_CaptainShota', image: ''},
  { id: 'EmoticonData_CDawg', image: ''},
  { id: 'EmoticonData_Cellbit', image: ''},
  { id: 'EmoticonData_Code', image: ''},
  { id: 'EmoticonData_Courage', image: ''},
  { id: 'EmoticonData_DrLupo', image: 'https://omegastrikers.wiki.gg/images/5/58/DrLupo_Emoticon.png' },
  { id: 'EmoticonData_Ducky', image: 'https://omegastrikers.wiki.gg/images/d/de/Ducky_Emoticon.png' },
  { id: 'EmoticonData_Dyrus', image: 'https://omegastrikers.wiki.gg/images/3/38/Dyrus_Emoticon.png' },
  { id: 'EmoticonData_Egoraptor', image: ''},
  { id: 'EmoticonData_Enviosity', image: 'https://omegastrikers.wiki.gg/images/7/74/Enviosity_Emoticon.png' },
  { id: 'EmoticonData_Fumi', image: ''},
  { id: 'EmoticonData_FumikoHoshi', image: ''},
  { id: 'EmoticonData_Fuslie', image: '' },
  { id: 'EmoticonData_GameGrumps', image: ''},
  { id: 'EmoticonData_Guchitsubo', image: ''},
  { id: 'EmoticonData_Hafu', image: '' },
  { id: 'EmoticonData_Hanjou', image: ''},
  { id: 'EmoticonData_IceStream', image: ''},
  { id: 'EmoticonData_IKeepItTaco', image: '' },
  { id: 'EmoticonData_Japanalysis', image: ''},
  { id: 'EmoticonData_Jrokez', image: ''},
  { id: 'EmoticonData_K4sen', image: ''},
  { id: 'EmoticonData_KinbutaKyo', image: ''},
  { id: 'EmoticonData_Lily', image: '' },
  { id: 'EmoticonData_Lirik', image: ''},
  { id: 'EmoticonData_LJoga', image: ''},
  { id: 'EmoticonData_Ludwig', image: ''},
  { id: 'EmoticonData_Mang0', image: ''},
  { id: 'EmoticonData_Mely', image: ''},
  { id: 'EmoticonData_Meteos', image: ''},
  { id: 'EmoticonData_Moist', image: '' },
  { id: 'EmoticonData_MyMrFruit', image: ''},
  { id: 'EmoticonData_Necrit', image: ''},
  { id: 'EmoticonData_Nemu', image: ''},
  { id: 'EmoticonData_Nyanners', image: ''},
  { id: 'EmoticonData_Obo', image: ''},
  { id: 'EmoticonData_Onigiri', image: ''},
  { id: 'EmoticonData_OoenoTakayuki', image: ''},
  { id: 'EmoticonData_Radda', image: ''},
  { id: 'EmoticonData_Rakin', image: '' },
  { id: 'EmoticonData_Rayditz', image: '' },
  { id: 'EmoticonData_Rejekun', image: ''},
  { id: 'EmoticonData_RomainLive', image: ''},
  { id: 'EmoticonData_Ross', image: ''},
  { id: 'EmoticonData_SanninShow', image: ''},
  { id: 'EmoticonData_Scarra', image: ''},
  { id: 'EmoticonData_Shaka', image: ''},
  { id: 'EmoticonData_SKJVillage', image: ''},
  { id: 'EmoticonData_Sneaky', image: ''},
  { id: 'EmoticonData_Sonho', image: ''},
  { id: 'EmoticonData_Sp4zie', image: ''},
  { id: 'EmoticonData_SPYGEA', image: ''},
  { id: 'EmoticonData_Sumomo', image: ''},
  { id: 'EmoticonData_Sykkuno', image: '' },
  { id: 'EmoticonData_Taiji', image: ''},
  { id: 'EmoticonData_TeamEqwaak', image: ''},
  { id: 'EmoticonData_TeamOJ', image: ''},
  { id: 'EmoticonData_TeamQueso', image: ''},
  { id: 'EmoticonData_Techzz', image: ''},
  { id: 'EmoticonData_TimTheTatman', image: ''},
  { id: 'EmoticonData_Tori', image: '' },
  { id: 'EmoticonData_Tuonto', image: '' },
  { id: 'EmoticonData_UNStrikers', image: ''},
  { id: 'EmoticonData_Uthenera', image: ''},
  { id: 'EmoticonData_Valkyrae', image: ''},
  { id: 'EmoticonData_Vernias', image: ''},
  { id: 'EmoticonData_Vienna', image: '' },
  { id: 'EmoticonData_xQc', image: ''},
  { id: 'EmoticonData_Yakkocmm', image: ''},
  { id: 'EmoticonData_Yoda', image: ''},
  { id: 'EmoticonData_zEmerson', image: ''},
  { id: 'EmoticonData_ZentreyaSalt', image: ''},
  { id: 'EmoticonData_Zeroljuin', image: ''},

  { id: 'EmoticonData_ALBERTA', image: 'https://omegastrikers.wiki.gg/images/5/54/University_of_Alberta_Esports_Association_Emoticon.png' }, // schools
  // { id: 'EmoticonData_ANGELO', image: '' },
  { id: 'EmoticonData_ASHLAND', image: 'https://omegastrikers.wiki.gg/images/e/e0/Ashland_Esports_Emoticon.png' },
  { id: 'EmoticonData_ASU_Esports_Association', image: 'https://omegastrikers.wiki.gg/images/9/90/ASU_Esports_Association_Emoticon.png' },
  // { id: 'EmoticonData_AUBURN', image: '' },
  { id: 'EmoticonData_BALTIC', image: 'https://omegastrikers.wiki.gg/images/4/46/Baltic_Esports_Kiel_Emoticon.png' },
  { id: 'EmoticonData_Boston_College_Gaming', image: 'https://omegastrikers.wiki.gg/images/a/a2/Boston_College_Gaming_Emoticon.png' },
  { id: 'EmoticonData_BPC', image: 'https://omegastrikers.wiki.gg/images/3/39/Brewton-Parker_Esports_Emoticon.png' },
  { id: 'EmoticonData_BRIARCLIFF', image: 'https://omegastrikers.wiki.gg/images/1/1a/Briar_Cliff_Esports_Emoticon.png' },
  { id: 'EmoticonData_BROWN', image: 'https://omegastrikers.wiki.gg/images/5/5b/Brown_Esports_Emoticon.png' },
  { id: 'EmoticonData_Bruin_Gaming', image: 'https://omegastrikers.wiki.gg/images/f/fd/Bruin_Gaming_Emoticon.png' },
  { id: 'EmoticonData_CARLETON', image: 'https://omegastrikers.wiki.gg/images/a/a8/Carleton_Esports_Emoticon.png' },
  { id: 'EmoticonData_CHICO', image: 'https://omegastrikers.wiki.gg/images/5/5f/CSU_Chico_Emoticon.png' },
  { id: 'EmoticonData_Clemson_Esports', image: 'https://omegastrikers.wiki.gg/images/a/ac/Clemson_Esports_Emoticon.png' },
  { id: 'EmoticonData_CMU', image: 'https://omegastrikers.wiki.gg/images/1/10/CMU_Esports_Emoticon.png' },
  { id: 'EmoticonData_COLORADO', image: 'https://omegastrikers.wiki.gg/images/9/96/Colorado_State_Unversity_Emoticon.png' },
  // { id: 'EmoticonData_CONCORDIA', image: '' },
  { id: 'EmoticonData_COOG', image: 'https://omegastrikers.wiki.gg/images/9/95/Coog_Gaming_%26_Esports_Emoticon.png' },
  { id: 'EmoticonData_CSUDH', image: 'https://omegastrikers.wiki.gg/images/f/ff/Esports_at_CSUDH_Emoticon.png' },
  { id: 'EmoticonData_CSULB', image: 'https://omegastrikers.wiki.gg/images/e/ee/CSULB_Esports_and_Gaming_Association_Emoticon.png' },
  { id: 'EmoticonData_DALHOUSIE', image: 'https://omegastrikers.wiki.gg/images/d/d2/Dalhousie_Gaming_and_Esports_Society_Emoticon.png' },
  { id: 'EmoticonData_DALLAS', image: 'https://omegastrikers.wiki.gg/images/1/11/UTD_Esports_Emoticon.png' },
  { id: 'EmoticonData_DEPAUL', image: 'https://omegastrikers.wiki.gg/images/4/42/DePaul_Esports_Emoticon.png' },
  { id: 'EmoticonData_DREXEL', image: 'https://omegastrikers.wiki.gg/images/7/77/Drexel_Esports_Emoticon.png' },
  { id: 'EmoticonData_DRURY', image: 'https://omegastrikers.wiki.gg/images/5/5b/Drury_Esports_Emoticon.png' },
  { id: 'EmoticonData_DUSSELDORF', image: 'https://omegastrikers.wiki.gg/images/a/ae/D%C3%BCsseldorf_Gaming_Emoticon.png' },
  { id: 'EmoticonData_EASTERN', image: 'https://omegastrikers.wiki.gg/images/c/c5/Eastern_Eagles_Emoticon.png' },
  { id: 'EmoticonData_ECU', image: 'https://omegastrikers.wiki.gg/images/7/78/ECU_Esports_and_Gaming_Emoticon.png' },
  { id: 'EmoticonData_Esports_Club_at_Florida_State', image: 'https://omegastrikers.wiki.gg/images/3/35/Esports_Club_at_Florida_State_Emoticon.png' },
  { id: 'EmoticonData_ESUG', image: 'https://omegastrikers.wiki.gg/images/d/dc/E-Sport_Union_G%C3%B6ttingen_Emoticon.png' },
  { id: 'EmoticonData_ETSU', image: 'https://omegastrikers.wiki.gg/images/3/3a/ETSU_Esports_Emoticon.png' },
  { id: 'EmoticonData_FANSHAWE', image: 'https://omegastrikers.wiki.gg/images/b/b4/Fanshawe_Fuel_Emoticon.png' },
  { id: 'EmoticonData_FERRIS', image: 'https://omegastrikers.wiki.gg/images/f/fa/Ferris_Esports_Emoticon.png' },
  { id: 'EmoticonData_FGCU', image: 'https://omegastrikers.wiki.gg/images/c/cc/FGCU_Esports_Emoticon.png' },
  { id: 'EmoticonData_FISHER', image: 'https://omegastrikers.wiki.gg/images/5/5c/Fisher_Esports.png' },
  { id: 'EmoticonData_Garden_State_Esports', image: 'https://omegastrikers.wiki.gg/images/1/19/Garden_State_Esports_Emoticon.png' },
  { id: 'EmoticonData_GCU', image: 'https://omegastrikers.wiki.gg/images/7/71/GCU_Esports_Emoticon.png' },
  { id: 'EmoticonData_GEORGIATECH', image: 'https://omegastrikers.wiki.gg/images/3/35/Georgia_Tech_Esports_Emoticon.png' },
  { id: 'EmoticonData_GMU', image: 'https://omegastrikers.wiki.gg/images/2/22/George_Mason_Patriots_Emoticon.png' },
  { id: 'EmoticonData_HAMBURGER', image: 'https://omegastrikers.wiki.gg/images/d/d2/Hamburger_Haie_Emoticon.png' },
  { id: 'EmoticonData_HARRISBURG', image: 'https://omegastrikers.wiki.gg/images/7/75/Harrisburg_University_Esports_Club_Emoticon.png' },
  { id: 'EmoticonData_HAWAII', image: 'https://omegastrikers.wiki.gg/images/a/a4/UH_Esports_Emoticon.png' },
  { id: 'EmoticonData_IEN', image: 'https://omegastrikers.wiki.gg/images/1/10/Indiana_Esports_Network_Emoticon.png' },
  { id: 'EmoticonData_IHSEA', image: 'https://omegastrikers.wiki.gg/images/d/d9/Illinois_High_School_Esports_Association_Emoticon.png' },
  { id: 'EmoticonData_Illini_Esports', image: 'https://omegastrikers.wiki.gg/images/c/ca/Illini_Esports_Emoticon.png' },
  { id: 'EmoticonData_ILLINOISTECH', image: 'https://omegastrikers.wiki.gg/images/7/76/Illinois_Tech_Esports_Emoticon.png' },
  { id: 'EmoticonData_INDIANA', image: 'https://omegastrikers.wiki.gg/images/5/52/Indiana_University_Gaming_%26_Esports_Emoticon.png' },
  { id: 'EmoticonData_JUNIATA', image: 'https://omegastrikers.wiki.gg/images/9/96/Juniata_College_Esports_Emoticon.png' },
  { id: 'EmoticonData_KEAN', image: 'https://omegastrikers.wiki.gg/images/8/84/Kean_Esports_Club_Emoticon.png' },
  { id: 'EmoticonData_KENNESAW', image: 'https://omegastrikers.wiki.gg/images/6/6a/Kennesaw_State_Esports_Emoticon.png' },
  { id: 'EmoticonData_KING', image: 'https://omegastrikers.wiki.gg/images/d/da/King_Tornado_Emoticon.png' },
  { id: 'EmoticonData_KUTZTOWN', image: 'https://omegastrikers.wiki.gg/images/1/1b/Kutztown_Esports_Emoticon.png' },
  { id: 'EmoticonData_LAKELAND', image: 'https://omegastrikers.wiki.gg/images/e/ea/Lakeland_University_Esports_Emoticon.png' },
  { id: 'EmoticonData_LANGARA', image: 'https://omegastrikers.wiki.gg/images/c/cf/Langara_Esports_Emoticon.png' },
  { id: 'EmoticonData_Liberty_Esports', image: 'https://omegastrikers.wiki.gg/images/f/f1/Liberty_Esports_Emoticon.png' },
  { id: 'EmoticonData_LONGHORN', image: 'https://omegastrikers.wiki.gg/images/5/54/Longhorn_Gaming_Emoticon.png' },
  { id: 'EmoticonData_MCMASTER', image: 'https://omegastrikers.wiki.gg/images/a/ad/McMaster_Esports_Emoticon.png' },
  { id: 'EmoticonData_Mississippi_State_University_Esports', image: 'https://omegastrikers.wiki.gg/images/8/8c/Mississippi_State_University_Esports_Emoticon.png' },
  { id: 'EmoticonData_MONTEVALLO', image: 'https://omegastrikers.wiki.gg/images/4/49/Montevallo_Esports_Emoticon.png' },
  { id: 'EmoticonData_MOUNTUNION', image: 'https://omegastrikers.wiki.gg/images/8/89/Mount_Union_Esports_Emoticon.png' },
  { id: 'EmoticonData_MTSU', image: 'https://omegastrikers.wiki.gg/images/7/7d/MTSU_Epsorts_Emoticon.png' },
  { id: 'EmoticonData_MURRAY', image: 'https://omegastrikers.wiki.gg/images/d/d1/Murray_State_Esports_Emoticon.png' },
  { id: 'EmoticonData_NCSTATE', image: 'https://omegastrikers.wiki.gg/images/d/d8/Esports_at_NC_State_Emoticon.png' },
  { id: 'EmoticonData_NEWARK', image: 'https://omegastrikers.wiki.gg/images/5/54/Rutgers_Newark_Gaming_Club_Emoticon.png' },
  { id: 'EmoticonData_NINER', image: 'https://omegastrikers.wiki.gg/images/c/c1/Niner_Esports_Emoticon.png' },
  { id: 'EmoticonData_NJIT', image: 'https://omegastrikers.wiki.gg/images/4/47/NJIT_Esports_Emoticon.png' },
  { id: 'EmoticonData_NORTHWOOD', image: 'https://omegastrikers.wiki.gg/images/7/76/Northwood_Esports_Emoticon.png' },
  { id: 'EmoticonData_NVCC', image: 'https://omegastrikers.wiki.gg/images/b/b3/Nighthawks_Esports_Emoticon.png' },
  { id: 'EmoticonData_NWCIOWA', image: 'https://omegastrikers.wiki.gg/images/4/47/Northwestern_Esports_Emoticon.png' },
  { id: 'EmoticonData_Ohio_Northern_University_Esports', image: 'https://omegastrikers.wiki.gg/images/7/7e/Ohio_Northern_University_Esports_Emoticon.png' },
  { id: 'EmoticonData_OHIOSTATE', image: 'https://omegastrikers.wiki.gg/images/9/9a/Buckeye_Gaming_Collective_Emoticon.png' },
  { id: 'EmoticonData_Oklahoma_Wesleyan_University', image: 'https://omegastrikers.wiki.gg/images/6/63/Oklahoma_Wesleyan_University_Emoticon.png' },
  { id: 'EmoticonData_OLEMISS', image: 'https://omegastrikers.wiki.gg/images/9/9b/Ole_Miss_Esports_Emoticon.png' },
  // { id: 'EmoticonData_OSE', image: '' },
  { id: 'EmoticonData_Purdue_University_Gamers_Group', image: 'https://omegastrikers.wiki.gg/images/1/1e/Purdue_University_Gamers_Group_Emoticon.png' },
  { id: 'EmoticonData_REDBIRD', image: 'https://omegastrikers.wiki.gg/images/a/a3/Redbird_Gaming_Emoticon.png' },
  { id: 'EmoticonData_RIVERSIDE', image: 'https://omegastrikers.wiki.gg/images/e/e3/Highlander_Gaming_Emoticon.png' },
  { id: 'EmoticonData_ROLLINS', image: 'https://omegastrikers.wiki.gg/images/3/39/Rollins_College_Esports_Emoticon.png' },
  { id: 'EmoticonData_RSU', image: 'https://omegastrikers.wiki.gg/images/d/d7/RSU_Esports_Emoticon.png' },
  { id: 'EmoticonData_Rutgers_Esports', image: 'https://omegastrikers.wiki.gg/images/8/8c/Rutgers_Esports_Emoticon.png' },
  { id: 'EmoticonData_RWU_Esports', image: 'https://omegastrikers.wiki.gg/images/5/5a/RWU_Esports_Emoticon.png' },
  // { id: 'EmoticonData_SAGU', image: '' },
  { id: 'EmoticonData_Saint_Louis_University_Esports', image: 'https://omegastrikers.wiki.gg/images/4/4b/Saint_Louis_University_Esports_Emoticon.png' },
  { id: 'EmoticonData_SAINTMARY', image: 'https://omegastrikers.wiki.gg/images/5/5a/USM_Esports_Emoticon.png' },
  { id: 'EmoticonData_SCAD', image: 'https://omegastrikers.wiki.gg/images/a/ad/SCAD_Esports_Emoticon.png' },
  { id: 'EmoticonData_SCHREINER', image: 'https://omegastrikers.wiki.gg/images/0/0b/Schreiner_Esports_Emoticon.png' },
  { id: 'EmoticonData_SEMO', image: 'https://omegastrikers.wiki.gg/images/a/a8/SEMO_Esports_Emoticon.png' },
  { id: 'EmoticonData_SHENANDOAH', image: 'https://omegastrikers.wiki.gg/images/6/60/Shenandoah_Esports_Club_Emoticon.png' },
  { id: 'EmoticonData_Sheridan_Esports', image: 'https://omegastrikers.wiki.gg/images/3/3c/Sheridan_Esports_Emoticon.png' },
  { id: 'EmoticonData_Slippery_Rock_Esports', image: 'https://omegastrikers.wiki.gg/images/d/d4/Slippery_Rock_Esports_Emoticon.png' },
  { id: 'EmoticonData_SPARTANS', image: 'https://omegastrikers.wiki.gg/images/2/21/Spartan_Esports_Emoticon.png' },
  { id: 'EmoticonData_STCLAIR', image: 'https://omegastrikers.wiki.gg/images/5/5f/St._Clair_Saints_Esports_Emoticon.png' },
  { id: 'EmoticonData_STEVENS', image: 'https://omegastrikers.wiki.gg/images/e/ed/Stevens_Esports_Emoticon.png' },
  { id: 'EmoticonData_STOCKTON', image: 'https://omegastrikers.wiki.gg/images/5/5b/Stockton_Esports_Emoticon.png' },
  { id: 'EmoticonData_STOUT', image: 'https://omegastrikers.wiki.gg/images/c/c9/Stout_Esports_Emoticon.png' },
  { id: 'EmoticonData_SUNYEMPIRE', image: 'https://omegastrikers.wiki.gg/images/8/8c/SUNY_Empire_Esports_Emoticon.png' },
  // { id: 'EmoticonData_TAMU', image: '' },
  { id: 'EmoticonData_Temple_Esports', image: 'https://omegastrikers.wiki.gg/images/e/e5/Temple_Esports_Emoticon.png' },
  { id: 'EmoticonData_TMU', image: 'https://omegastrikers.wiki.gg/images/e/e8/TMU_Esports_Emoticon.png' },
  { id: 'EmoticonData_TNTECH', image: 'https://omegastrikers.wiki.gg/images/1/1f/Tennessee_Tech_Esports_Club_Emoticon.png' },
  { id: 'EmoticonData_TRINE', image: 'https://omegastrikers.wiki.gg/images/e/e9/Trine_Esports_Emoticon.png' },
  { id: 'EmoticonData_TRITON', image: 'https://omegastrikers.wiki.gg/images/8/8e/Triton_Gaming_Emoticon.png' },
  { id: 'EmoticonData_TXST_Esports', image: 'https://omegastrikers.wiki.gg/images/8/8c/TXST_Esports_Emoticon.png' },
  { id: 'EmoticonData_UAB', image: 'https://omegastrikers.wiki.gg/images/c/ca/Good_Games_UAB_Emoticon.png' },
  { id: 'EmoticonData_UBC', image: 'https://omegastrikers.wiki.gg/images/1/1b/UBC_Esports_Emoticon.png' },
  { id: 'EmoticonData_UCF_Esports', image: 'https://omegastrikers.wiki.gg/images/f/f2/Esports_at_UCF_Emoticon.png' },
  // { id: 'EmoticonData_UCESPORTS', image: '' },
  { id: 'EmoticonData_UCSB', image: 'https://omegastrikers.wiki.gg/images/6/64/UCSB_Esports_Emoticon.png' },
  { id: 'EmoticonData_UHSP', image: 'https://omegastrikers.wiki.gg/images/3/32/UHSP_Eutectics_Esports_Emoticon.png' },
  { id: 'EmoticonData_UNC_Chapel_Hill_Esports', image: 'https://omegastrikers.wiki.gg/images/c/ca/UNC_Chapel_Hill_Esports_Emoticon.png' },
  { id: 'EmoticonData_uOttawa_Esports', image: 'https://omegastrikers.wiki.gg/images/1/17/UOttawa_Esports_Emoticon.png' },
  { id: 'EmoticonData_UW_Stout_Esports', image: 'https://omegastrikers.wiki.gg/images/d/d8/UW-Stout_Esports_Emoticon.png' },
  { id: 'EmoticonData_UWRF_Esports', image: 'https://omegastrikers.wiki.gg/images/1/1f/UWRF_Esports_Emoticon.png' },
  { id: 'EmoticonData_WAKE', image: 'https://omegastrikers.wiki.gg/images/5/5f/Wake_Forest_Esports_Association_Emoticon.png' },
  { id: 'EmoticonData_WARTBURG', image: 'https://omegastrikers.wiki.gg/images/c/cf/Wartburg_Esports_Emoticon.png' },
  { id: 'EmoticonData_Waterloo_Warriors', image: 'https://omegastrikers.wiki.gg/images/6/6b/Waterloo_Warriors_Emoticon.png' },
  { id: 'EmoticonData_WEBER', image: 'https://omegastrikers.wiki.gg/images/2/2a/WSU_Esports_Emoticon.png' },
  { id: 'EmoticonData_WICHITA', image: 'https://omegastrikers.wiki.gg/images/e/e8/Shockers_Emoticon.png' },
  { id: 'EmoticonData_WILDCATS', image: 'https://omegastrikers.wiki.gg/images/c/c7/Wildcat_Gaming_Club_Emoticon.png' },
  { id: 'EmoticonData_Winthrop_University', image: 'https://omegastrikers.wiki.gg/images/0/08/Winthrop_University_Emoticon.png' },

]

export default emoticons