const emoticons = [
  { id: 'EmoticonData_AngelicSupportMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AtlasPray-512x512.png' },
  { id: 'EmoticonData_AngelicSupportMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AtlasSigh-512x512.webp' },
  { id: 'EmoticonData_ChaoticRocketeerMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_LunaGoodJob-512x512.png' },
  { id: 'EmoticonData_ChaoticRocketeerMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_LunaCalculating-512x512.webp' },
  { id: 'EmoticonData_CleverSummonerMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoBlankStare-512x512.png' },
  { id: 'EmoticonData_CleverSummonerMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoShake-512x512.webp' },
  { id: 'EmoticonData_EDMOniMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_OctaviaShrug-512x512.png' },
  { id: 'EmoticonData_EDMOniMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_OactaviaYawn-512x512.webp' },
  { id: 'EmoticonData_EmpoweringEnchanterMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EraShy-512x512.png' },
  { id: 'EmoticonData_EmpoweringEnchanterMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EraThisIsFine-512x512.webp' },
  { id: 'EmoticonData_FlashySwordsmanMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_ZentaroPause-512x512.png' },
  { id: 'EmoticonData_FlashySwordsmanMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_ZentaroLaugh-512x512.webp' },
  { id: 'EmoticonData_FlexibleBrawlerMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteSuccess-512x512.png' },
  { id: 'EmoticonData_FlexibleBrawlerMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteDetermined-512x512.webp' },
  { id: 'EmoticonData_HulkingBeastMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_XFleX-512x512.png' },
  { id: 'EmoticonData_HulkingBeastMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_XMenace-512x512.webp' },
  { id: 'EmoticonData_MagicalPlaymakerMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AimiLaser-512x512.png' },
  { id: 'EmoticonData_MagicalPlaymakerMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AimiKeyboard-512x512.webp' },
  { id: 'EmoticonData_ManipulatingMastermindMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RuneCreepy-512x512.png' },
  { id: 'EmoticonData_ManipulatingMastermindMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RuneSurprised-512x512.webp' },
  { id: 'EmoticonData_NimbleBlasterMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DrekarThink-512x512.png' },
  { id: 'EmoticonData_NimbleBlasterMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DrekarMadge-512x512.webp' },
  { id: 'EmoticonData_RockOniMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RockOniBleh-512x512.png' },
  { id: 'EmoticonData_RockOniMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_VyceRockOn-512x512.webp' },
  { id: 'EmoticonData_ShieldUserMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AsherSus-512x512.png' },
  { id: 'EmoticonData_ShieldUserMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AsherYikes-512x512.webp' },
  { id: 'EmoticonData_SpeedySkirmisherMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_KaiShrug-512x512.png' },
  { id: 'EmoticonData_SpeedySkirmisherMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_KaiBurn-512x512.webp' },
  { id: 'EmoticonData_StalwartProtectorMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuOmega-512x512.png' },
  { id: 'EmoticonData_StalwartProtectorMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuLetsGo-512x512.webp' },
  { id: 'EmoticonData_TempoSniperMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EstelleRose-512x512.png' },
  { id: 'EmoticonData_TempoSniperMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EstelleKiss-512x512.webp' },
  { id: 'EmoticonData_WhipFighterMastery', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RasmusAngry-512x512.png' },
  { id: 'EmoticonData_WhipFighterMasteryAnimated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RasmusShocked-512x512.webp' },
  { id: 'EmoticonData_AimiCry', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AimiCry-png'},
  { id: 'EmoticonData_AimiNoted', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AimiNoted-512x512.webp'},
  { id: 'EmoticonData_AimiSweat', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AimiSweat-512x512.webp'},
  { id: 'EmoticonData_AsherPog', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AsherPog-512x512.png'},
  { id: 'EmoticonData_AtlasThink', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AtlasThink-512x512.png'},
  { id: 'EmoticonData_AtlasThumbsUp', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AtlasNice-512x512.png'},
  { id: 'EmoticonData_DrekarBusiness', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DrekarBusiness-512x512.png'},
  { id: 'EmoticonData_EraIsThis', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EraIsThis-512x512.png'},
  { id: 'EmoticonData_EraRainDrop', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EraRaindropSad-512x512.png'},
  { id: 'EmoticonData_JulietteCopium', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteCopium-512x512.png'},
  { id: 'EmoticonData_LunaCry', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_LunaCry-512x512.png'},
  { id: 'EmoticonData_LunaGlasses', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_LunaGlasses-512x512.png'},
  { id: 'EmoticonData_LunaWizard', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_LunaWizardOrb-512x512.png'},
  { id: 'EmoticonData_RasmusPray', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RasmusPray-512x512.png'},
  { id: 'EmoticonData_RuneClone', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RuneClone-512x512.png'},
  { id: 'EmoticonData_RuneYouAreMe', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RuneYou-512x512.png'},
  { id: 'EmoticonData_XGigachad', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_XGigaChad-512x512.png'},
  { id: 'EmoticonData_ZentaroDeadge', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_ZentaroDeadge-512x512.png'},
  { id: 'EmoticonData_AiMiCatSalad', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AiMiCatSalad-512x512.png'},
  { id: 'EmoticonData_AiMiFree', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AiMiFree-512x512.png'},
  { id: 'EmoticonData_AiMiNom', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AiMiNOM-512x512.png'},
  { id: 'EmoticonData_AiMiPat', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AiMiPat-512x512.png'},
  { id: 'EmoticonData_AiMiShocked', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AiMiShock-512x512.png'},
  { id: 'EmoticonData_AiMiSmug', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AiMiSmug-512x512.png'},
  { id: 'EmoticonData_AsherCheer', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AsherCheer-512x512.png'},
  { id: 'EmoticonData_AsherDisgust', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AsherDisgust-512x512.png'},
  { id: 'EmoticonData_AsherPoint', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AsherPoint-512x512.png'},
  { id: 'EmoticonData_BlobBlushing', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_BlushingBlob-512x512.png'},
  { id: 'EmoticonData_BlobboCheer', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobboCheer-512x512.png'},
  { id: 'EmoticonData_BlobboLove', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobboLove-512x512.png'},
  { id: 'EmoticonData_BlobboParty', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobboParty-512x512.png'},
  { id: 'EmoticonData_BlobConfused', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_ConfusedBlob-512x512.png'},
  { id: 'EmoticonData_BlobHappy', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_HappyBlob-512x512.png'},
  { id: 'EmoticonData_BlobMad', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_MadBlob-512x512.png'},
  { id: 'EmoticonData_BlobSad', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_SadBlob-512x512.png'},
  { id: 'EmoticonData_BPS1Badge1', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_Season1BadgeTier3-512x512.png'},
  { id: 'EmoticonData_Challenger', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_UI_RankedEmblem_Master_Low.T_UI_RankedEmblem_Master_Low'},
  { id: 'EmoticonData_DefaultThumbsUp', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_ThumbsUp-512x512.png'},
  { id: 'EmoticonData_Diamond', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_UI_RankedEmblem_Diamond_Low.T_UI_RankedEmblem_Diamond_Low'},
  { id: 'EmoticonData_DJAtlas', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DJAtlas-512x512.webp'},
  { id: 'EmoticonData_DrekarDetective', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DrexWhat-512x512.png'},
  { id: 'EmoticonData_DrekarSpeechless', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DrexPog.T_DrexPog'},
  { id: 'EmoticonData_DubuBop', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuNOM.T_DubuNOM'},
  { id: 'EmoticonData_DubuCurious', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuNyo-512x512.png'},
  { id: 'EmoticonData_DubuOne', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuOne-512x512.png'},
  { id: 'EmoticonData_DubuPanicked', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuConcern-512x512.png'},
  { id: 'EmoticonData_DubuShocked', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_DubuShocked-512x512.png'},
  { id: 'EmoticonData_EraUwu', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EraUwu-512x512.png'},
  { id: 'EmoticonData_EstelleFacepalm', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EstelleFacepalm-512x512.png'},
  { id: 'EmoticonData_EstelleGloat', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EstelleOho-512x512.png'},
  { id: 'EmoticonData_EternalFlameDubu', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_EternalFlameDubu-512x512.png'},
  { id: 'EmoticonData_Founder', image: 'https://static.strikr.gg/file/Strikr/emoticon/OdysseyProfileLogo_128.png'},
  { id: 'EmoticonData_Gold', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_UI_RankedEmblem_Gold_Low.T_UI_RankedEmblem_Gold_Low'},
  { id: 'EmoticonData_Halloween_Duboo', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Duboo-512x512.png'},
  { id: 'EmoticonData_Halloween_Era_Coffin', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EraDeadge-512x512.png'},
  { id: 'EmoticonData_Halloween_Estelle_Nurse', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_EstelleHypers-512x512.png'},
  { id: 'EmoticonData_Halloween_Juno_Clown', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoClown-512x512.png'},
  { id: 'EmoticonData_Halloween_XWerewolf', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_XWerewolf-512x512.png'},
  { id: 'EmoticonData_HyperX', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_HyperX-512x512.png'},
  { id: 'EmoticonData_IdolAimiHeart', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_IdolAimiHeart-512x512.png'},
  { id: 'EmoticonData_JulietteComfy', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteComfy-512x512.png'},
  { id: 'EmoticonData_JulietteCool', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteEz-512x512.png'},
  { id: 'EmoticonData_JulietteDefeated', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteCryge-512x512.png'},
  { id: 'EmoticonData_JulietteHeart', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteHeart-512x512.png'},
  { id: 'EmoticonData_JulietteLightsOut', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_LightsOut-512x512.png'},
  { id: 'EmoticonData_JuliettePunch', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JuliettePunch-512x512.png'},
  { id: 'EmoticonData_JulietteRave', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteRave-512x512.png'},
  { id: 'EmoticonData_JulietteThumbsUp', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteThumbsUp-512x512.png'},
  { id: 'EmoticonData_JulietteVibe', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JulietteVibe-512x512.png'},
  { id: 'EmoticonData_JunoBop', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BigBopJuno-512x512.png'},
  { id: 'EmoticonData_JunoCute', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoHappy-512x512.png'},
  { id: 'EmoticonData_JunoDevious', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoHype-512x512.png'},
  { id: 'EmoticonData_JunoFight', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoFight-512x512.png'},
  { id: 'EmoticonData_JunoGawk', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoZoom-512x512.png'},
  { id: 'EmoticonData_JunoGiggle', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoLul-512x512.png'},
  { id: 'EmoticonData_JunoShy', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoShy-512x512.png'},
  { id: 'EmoticonData_JunoSleep', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoSleep-512x512.png'},
  { id: 'EmoticonData_JunoSnackTime', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoPopcorn-512x512.png'},
  { id: 'EmoticonData_JunoStarry', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoWOW.png'},
  { id: 'T_JunoWOW', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_JunoWOW.png'},
  { id: 'EmoticonData_KaiGlamour', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_KaiSmirk-512x512.png'},
  { id: 'EmoticonData_KaiShambles', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_KaiFine-512x512.png'},
  { id: 'EmoticonData_LunaPeace', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_LunaPeace-512x512.png'},
  { id: 'EmoticonData_MusicVS_EdmOni1', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_OactaviaYawn-512x512.png'},
  { id: 'EmoticonData_MusicVS_RockOni', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_GuitarOniBleh-512x512.png'},
  { id: 'EmoticonData_Omega', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_UI_RankedEmblem_Promethean.T_UI_RankedEmblem_Promethean'},
  { id: 'EmoticonData_Platinum', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_UI_RankedEmblem_Platinum_Low.T_UI_RankedEmblem_Platinum_Low'},
  { id: 'EmoticonData_RasmusAngry', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RasmusAngry-512x512.png'},
  { id: 'EmoticonData_RasmusShocked', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RasmusShocked-512x512.png'},
  { id: 'EmoticonData_RuneDespair', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RuneDespair-512x512.png'},
  { id: 'EmoticonData_RunePoor', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RunePoor-512x512.png'},
  { id: 'EmoticonData_RuneV', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_RuneV-512x512.png'},
  { id: 'EmoticonData_SoniiPepega', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_SoniiPepega-512x512.png'},
  { id: 'EmoticonData_SoniiSalute', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_SoniiSalute-512x512.png'},
  { id: 'EmoticonData_STARLEAGUE', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_STARLEAGUE-512x512.png'},
  { id: 'EmoticonData_TeamEDM', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeamEDM-512x512.png'},
  { id: 'EmoticonData_TeamRock', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeamRock-512x512.png'},
  { id: 'EmoticonData_TeaTimeDubu', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeaTimeDubu-512x512.png'},
  { id: 'EmoticonData_TeaTimeFini', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeaTimeFini-512x512.png'},
  { id: 'EmoticonData_TeaTimeMatcha', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeaTimeMatcha-512x512.png'},
  { id: 'EmoticonData_TeaTimeMilk', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeaTimeMilk-512x512.png'},
  { id: 'EmoticonData_TeaTimePumpkin', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeaTimePumpkin-512x512.png'},
  { id: 'EmoticonData_TeaTimeTaro', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_TeaTimeTaro-512x512.png'},
  { id: 'EmoticonData_T_Emoticon_WumpusFive', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_WumpusFive-512x512.png'},
  { id: 'EmoticonData_T_Emoticon_WumpusGoalie', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_WumpusGoalie-512x512.png'},
  { id: 'EmoticonData_T_Emoticon_WumpusStrike', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_Emoticon_WumpusStrike-512x512.png'},
  { id: 'EmoticonData_XRage', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_XRAGE-512x512.png'},
  { id: 'EmoticonData_BlobAssexual', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobAssexual-512x512.png'},
  { id: 'EmoticonData_BlobBissexual', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobBissexual-512x512.png'},
  { id: 'EmoticonData_BlobGay', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobGay-512x512.png'},
  { id: 'EmoticonData_BlobLesbian', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobLesbian-512x512.png'},
  { id: 'EmoticonData_BlobPansexual', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobPansexual-512x512.png'},
  { id: 'EmoticonData_BlobTrans', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobTrans-512x512.png'},
  { id: 'EmoticonData_BlobNonbinary', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobNonbinary-512x512.png'},
  { id: 'EmoticonData_BlobPride', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_BlobPride-512x512.png'},
  { id: 'EmoticonData_AtlasDefend', image: 'https://static.strikr.gg/file/Strikr/emoticon/T_AtlasDefend-512x512.webp'},
  { id: 'EmoticonData_ALBERTA', image: '' },
  { id: 'EmoticonData_ASHLAND', image: '' },
  { id: 'EmoticonData_ASU_Esports_Association', image: '' },
  { id: 'EmoticonData_AUBURN', image: '' },
  { id: 'EmoticonData_AiMiTank', image: 'https://omegastrikers.wiki.gg/images/3/3e/Tank_Ai.Mi_Emoticon.png' },
  { id: 'EmoticonData_AsherTank', image: 'https://omegastrikers.wiki.gg/images/c/c4/Asher_Tank.png' },
  { id: 'EmoticonData_AtlasTank', image: 'https://omegastrikers.wiki.gg/images/f/fe/Atlas_Tank.png' },
  { id: 'EmoticonData_DrekarTank', image: 'https://omegastrikers.wiki.gg/images/7/7f/Drekar_Tank.png' },
  { id: 'EmoticonData_DubuTank', image: 'https://omegastrikers.wiki.gg/images/3/30/Dubu_Tank.png' },
  { id: 'EmoticonData_EraTank', image: 'https://omegastrikers.wiki.gg/images/c/c3/Era_Tank.png' },
  { id: 'EmoticonData_EstelleTank', image: 'https://omegastrikers.wiki.gg/images/d/dc/Estelle_Tank.png' },
  { id: 'EmoticonData_FiniiTank', image: 'https://omegastrikers.wiki.gg/images/3/38/Finii_Tank.png' },
  { id: 'EmoticonData_JulietteTank', image: 'https://omegastrikers.wiki.gg/images/1/14/Juliette_Tank.png' },
  { id: 'EmoticonData_JunoTank', image: 'https://omegastrikers.wiki.gg/images/2/25/Juno_Tank.png' },
  { id: 'EmoticonData_KaiTank', image: 'https://omegastrikers.wiki.gg/images/c/c4/Kai_Tank.png' },
  { id: 'EmoticonData_KazanTank', image: 'https://omegastrikers.wiki.gg/images/3/3b/Kazan_Tank.png' },
  { id: 'EmoticonData_LunaTank', image: 'https://omegastrikers.wiki.gg/images/8/8d/Luna_Tank.png' },
  { id: 'EmoticonData_MakoTank', image: 'https://omegastrikers.wiki.gg/images/e/e0/Mako_Tank.png' },
  { id: 'EmoticonData_NaoTank', image: 'https://omegastrikers.wiki.gg/images/9/98/Nao_Tank.png' },
  { id: 'EmoticonData_OctaviaTank', image: 'https://omegastrikers.wiki.gg/images/6/6c/Octavia_Tank.png' },
  { id: 'EmoticonData_RasmusTank', image: 'https://omegastrikers.wiki.gg/images/d/d6/Rasmus_Tank.png' },
  { id: 'EmoticonData_RuneTank', image: 'https://omegastrikers.wiki.gg/images/6/68/Rune_Tank.png' },
  { id: 'EmoticonData_VyceTank', image: 'https://omegastrikers.wiki.gg/images/7/76/Vyce_Tank.png' },
  { id: 'EmoticonData_XTank', image: 'https://omegastrikers.wiki.gg/images/1/1e/X_Tank.png' },
  { id: 'EmoticonData_ZentaroTank', image: 'https://omegastrikers.wiki.gg/images/7/7d/Zentaro_Tank.png' },
  { id: 'EmoticonData_BALTIC', image: '' },
  { id: 'EmoticonData_BPC', image: '' },
  { id: 'EmoticonData_BPS1Badge1', image: '' },
  { id: 'EmoticonData_BriarCliff', image: '' },
  { id: 'EmoticonData_BROWN', image: '' },
  { id: 'EmoticonData_Blau3', image: '' },
  { id: 'EmoticonData_BlobboCheer', image: '' },
  { id: 'EmoticonData_BlobboParty', image: '' },
  { id: 'EmoticonData_Boston_College_Gaming', image: '' },
  { id: 'EmoticonData_Bruin_Gaming', image: '' },
  { id: 'EmoticonData_CARLETON', image: '' },
  { id: 'EmoticonData_CHICO', image: '' },
  { id: 'EmoticonData_CMU', image: '' },
  { id: 'EmoticonData_COLORADO', image: '' },
  { id: 'EmoticonData_COOG', image: '' },
  { id: 'EmoticonData_CSUDH', image: '' },
  { id: 'EmoticonData_ClarionVSEnergyTeam', image: '' },
  { id: 'EmoticonData_ClarionVSReward', image: '' },
  { id: 'EmoticonData_ClarionVSStrengthTeam', image: '' },
  { id: 'EmoticonData_ClarionVSTechTeam', image: '' },
  { id: 'EmoticonData_Colin', image: '' },
  { id: 'EmoticonData_DrLupo', image: '' },
  { id: 'EmoticonData_DrekarBlahBlah', image: '' },
  { id: 'EmoticonData_DrekarPeace', image: '' },
  { id: 'EmoticonData_DubuHuh', image: '' },
  { id: 'EmoticonData_DubuIceCream', image: '' },
  { id: 'EmoticonData_DubuYas', image: '' },
  { id: 'EmoticonData_Ducky', image: '' },
  { id: 'EmoticonData_Dyrus', image: '' },
  { id: 'EmoticonData_ETSU', image: '' },
  { id: 'EmoticonData_Enviosity', image: '' },
  { id: 'EmoticonData_Esports_Club_at_Florida_State', image: '' },
  { id: 'EmoticonData_FGCU', image: '' },
  { id: 'EmoticonData_Fuslie', image: '' },
  { id: 'EmoticonData_GCU', image: '' },
  { id: 'EmoticonData_GEORGIATECH', image: '' },
  { id: 'EmoticonData_Garden_State_Esports', image: '' },
  { id: 'EmoticonData_HAMBURGER', image: '' },
  { id: 'EmoticonData_HARRISBURG', image: '' },
  { id: 'EmoticonData_Hafu', image: '' },
  { id: 'EmoticonData_IHSEA', image: '' },
  { id: 'EmoticonData_IKeepItTaco', image: '' },
  { id: 'EmoticonData_INDIANA', image: '' },
  { id: 'EmoticonData_Illini_Esports', image: '' },
  { id: 'EmoticonData_Liberty_Esports', image: '' },
  { id: 'EmoticonData_Lily', image: '' },
  { id: 'EmoticonData_MTSU', image: '' },
  { id: 'EmoticonData_Mississippi_State_University_Esports', image: '' },
  { id: 'EmoticonData_Moist', image: '' },
  { id: 'EmoticonData_NVCC', image: '' },
  { id: 'EmoticonData_Ohio_Northern_University_Esports', image: '' },
  { id: 'EmoticonData_Oklahoma_Wesleyan_University', image: '' },
  { id: 'EmoticonData_ProLeagueVS', image: '' },
  { id: 'EmoticonData_ProLeagueVSByteBreaker', image: '' },
  { id: 'EmoticonData_ProLeagueVSClarionCorp', image: '' },
  { id: 'EmoticonData_ProLeagueVSDemonDrive', image: '' },
  { id: 'EmoticonData_ProLeagueVSEmberMonarchs', image: '' },
  { id: 'EmoticonData_ProLeagueVSFrostfire', image: '' },
  { id: 'EmoticonData_ProLeagueVSMaelstrom', image: '' },
  { id: 'EmoticonData_ProLeagueVSSSR', image: '' },
  { id: 'EmoticonData_Purdue_University_Gamers_Group', image: '' },
  { id: 'EmoticonData_RWU_Esports', image: '' },
  { id: 'EmoticonData_Rakin', image: '' },
  { id: 'EmoticonData_Rayditz', image: '' },
  { id: 'EmoticonData_Rutgers_Esports', image: '' },
  { id: 'EmoticonData_SADBOIS', image: '' },
  { id: 'EmoticonData_SPARTANS', image: '' },
  { id: 'EmoticonData_Saint_Louis_University_Esports', image: '' },
  { id: 'EmoticonData_Sheridan_Esports', image: '' },
  { id: 'EmoticonData_Slippery_Rock_Esports', image: '' },
  { id: 'EmoticonData_SoniiTrophy', image: '' },
  { id: 'EmoticonData_Sykkuno', image: '' },
  { id: 'EmoticonData_TNTECH', image: '' },
  { id: 'EmoticonData_Temple_Esports', image: '' },
  { id: 'EmoticonData_Tori', image: '' },
  { id: 'EmoticonData_Tuonto', image: '' },
  { id: 'EmoticonData_UBC', image: '' },
  { id: 'EmoticonData_UCF_Esports', image: '' },
  { id: 'EmoticonData_UCSB', image: '' },
  { id: 'EmoticonData_UNC_Chapel_Hill_Esports', image: '' },
  { id: 'EmoticonData_UWRF_Esports', image: '' },
  { id: 'EmoticonData_UW_Stout_Esports', image: '' },
  { id: 'EmoticonData_Vienna', image: '' },
  { id: 'EmoticonData_WICHITA', image: '' },
  { id: 'EmoticonData_WILDCATS', image: '' },
  { id: 'EmoticonData_Waterloo_Warriors', image: '' },
  { id: 'EmoticonData_Winthrop_University', image: '' },
  { id: 'EmoticonData_uOttawa_Esports', image: '' },
]

export default emoticons