export const TitleLookup = {
  TitleData_Abandoned: { en: 'Abandoned' },
  TitleData_Aesop: { en: 'Aesop' },
  TitleData_AllStar: { en: 'All-Star' },
  TitleData_AmongTheStars: { en: 'Among the Stars' },
  TitleData_AngelicSupportMastery: { en: 'Time Traveler' },
  TitleData_AscendingChampion: { en: 'Ascending Champion' },
  TitleData_BackpassBeast: { en: 'Backpass Beast' },
  TitleData_BestintheWest: { en: 'Best in the West' },
  TitleData_BetaReward: { en: 'The Eternal Flame' },
  TitleData_BlobWhisperer: { en: 'Blob Whisperer' },
  TitleData_Bomba: { en: 'Bomba!' },
  TitleData_BPS1Investor: { en: 'The Early Investor' },
  TitleData_BPS1Striker: { en: 'Beta Season Striker' },
  TitleData_BPS2Hotshot: { en: 'The Hotshot' },
  TitleData_BPS2Striker: { en: 'Season Two Striker' },
  TitleData_BravedtheTank: { en: 'Braved the Tank' },
  TitleData_BuiltDifferent: { en: 'Built Different' },
  TitleData_Caughtin4k: { en: 'Caught in 4k' },
  TitleData_CCLChampion: { en: 'CCL Champion' },
  TitleData_CCLFinalist: { en: 'CCL Finalist' },
  TitleData_CCLQualifier: { en: 'CCL Qualifier' },
  TitleData_CCLTop8: { en: 'CCL Top 8' },
  TitleData_ChaoticRocketeerMastery: { en: 'Chaotic' },
  TitleData_Chatter: { en: 'Chatter' },
  TitleData_ClarionCorpVS: { en: 'Test Subject' },
  TitleData_CleverSummonerMastery: { en: 'Blobbo Buddy' },
  TitleData_Clipmaster: { en: 'Clipmaster' },
  TitleData_Comfy: { en: 'Comfy' },
  TitleData_Competitor: { en: 'Competitor' },
  TitleData_Connoisseur: { en: 'Connoisseur' },
  TitleData_Contributor: { en: 'Contributor' },
  TitleData_CoveredinPaint: { en: 'Covered in Paint' },
  TitleData_Cracked: { en: 'Cracked' },
  TitleData_CreamOfTheCrop: { en: 'Cream of the Crop' },
  TitleData_Cringe: { en: 'Cringe' },
  TitleData_CrustaceanConnoisseur: { en: 'Crustacean Connoisseur' },
  TitleData_DeepEnd: { en: 'Deep End' },
  TitleData_Deity: { en: 'Deity' },
  TitleData_DemonQueuer: { en: 'Demon Queuer' },
  TitleData_DoubleCringe: { en: 'Double Cringe' },
  TitleData_DrumOniMastery: { en: 'Taiko Trailblazer' },
  TitleData_EDMOniMastery: { en: 'Virtuoso' },
  TitleData_EmpoweringEnchanterMastery: { en: 'Bewitched' },
  TitleData_EuroSage: { en: 'Euro Sage' },
  TitleData_FarewellBanner: { en: 'Promethean' },
  TitleData_FlashySwordsmanMastery: { en: 'Blade Master' },
  TitleData_FlexibleBrawlerMastery: { en: 'Rising Star' },
  TitleData_Founder: { en: 'Founding Member' },
  TitleData_GlitchCatShock: { en: 'Glitch Cat Shock!' },
  TitleData_GraduatingClass: { en: 'Graduating Class' },
  TitleData_GravityMageMastery: { en: 'Illusionist' },
  TitleData_HalfBaked: { en: 'Half-Baked' },
  TitleData_HallofFame: { en: 'Hall of Fame' },
  TitleData_Halloween_Pumpkin: { en: 'Pumpkin' },
  TitleData_Halloween_Spooky: { en: 'Spooky' },
  TitleData_HealerMastery: { en: 'Nao or Never' },
  TitleData_HulkingBeastMastery: { en: 'Excessive' },
  TitleData_HyperX: { en: 'HyperX Hero' },
  TitleData_IceCreamEnjoyer: { en: 'Ice Cream Enjoyer' },
  TitleData_Idol: { en: 'Idol' },
  TitleData_Irrefutable: { en: 'Irrefutable' },
  TitleData_KazAngler: { en: 'Kaz Angler' },
  TitleData_Knower: { en: 'Knower' },
  TitleData_KOChamp: { en: 'K.O. Champ' },
  TitleData_LateNightLobster: { en: 'Late Night Lobster' },
  TitleData_LivesbytheBrush: { en: 'Lives by the Brush' },
  TitleData_LivingCalculator: { en: 'Living Calculator' },
  TitleData_MagicalPlaymakerMastery: { en: 'Glitchy' },
  TitleData_ManipulatingMastermindMastery: { en: 'Sinister Shadow' },
  TitleData_MasterBrawler: { en: 'Expert Brawler' },
  TitleData_MasterSniper: { en: 'Expert Sniper' },
  TitleData_MeteoricRise: { en: 'Meteoric Rise' },
  TitleData_MostDangerousGame: { en: 'Most Dangerous Game' },
  TitleData_MovieStar: { en: 'Movie Star' },
  TitleData_NimbleBlasterMastery: { en: 'Space Invader' },
  TitleData_Nocturnal: { en: 'Nocturnal' },
  TitleData_None: { en: 'No title :(' },
  TitleData_o7: { en: 'o7' },
  TitleData_OniRelease: { en: 'Drum Breaker' },
  TitleData_OrbGobbler: { en: 'Orb Enjoyer' },
  TitleData_OutforLunch: { en: 'Out for Lunch' },
  TitleData_OwnGoaler: { en: 'Own Goaler' },
  TitleData_PBWM: { en: 'PBWM' },
  TitleData_Performer: { en: 'Performer' },
  TitleData_Picasso: { en: 'Picasso' },
  TitleData_PixelArtist: { en: 'Pixel Artist' },
  TitleData_ProcurestheRock: { en: 'Core Controller' },
  TitleData_ProGamer: { en: 'Pro Gamer' },
  TitleData_ProLeagueVS: { en: 'Finalist' },
  TitleData_ProYapper: { en: 'Pro Yapper' },
  TitleData_RAAAHHHHHH: { en: 'RAAAHHHHHH' },
  TitleData_ReadyForLiftoff: { en: 'Ready for Liftoff' },
  TitleData_RiseandGrind: { en: 'Rise & Grind' },
  TitleData_RisenAbove: { en: 'Risen Above' },
  TitleData_RockOniMastery: { en: 'Rock Star' },
  TitleData_S1Champion: { en: 'Beta Season Omega Striker' },
  TitleData_S1TournamentChampion: { en: 'S1 Tournament Champion' },
  TitleData_S1TournamentFlawless: { en: 'S1 Flawless Tournament Winner' },
  TitleData_S1TournamentLegend: { en: 'S1 Tournament Legend' },
  TitleData_S1TournamentWarrior: { en: 'S1 Tournament Warrior' },
  TitleData_S1TournamentWinner: { en: 'S1 Tournament Winner' },
  TitleData_S2Champion: { en: 'Season One Omega Striker' },
  TitleData_S2TournamentParticipant: { en: 'Ignited' },
  TitleData_ScalingForLateGame: { en: 'Scaling For Late Game' },
  TitleData_SeraStar: { en: 'SeraStar' },
  TitleData_ShieldUserMastery: { en: 'Unbreakable' },
  TitleData_ShinyGoldenMedal: { en: 'Shiny Golden Medal' },
  TitleData_SigmaStriker: { en: 'Sigma Striker' },
  TitleData_SitDownLilBro: { en: 'Sit Down Lil\' Bro' },
  TitleData_SkystheLimit: { en: 'Sky\'s the Limit' },
  TitleData_SpecializedTrainer: { en: 'Specialized Trainer' },
  TitleData_SpeedySkirmisherMastery: { en: 'Prodigy' },
  TitleData_StalwartProtectorMastery: { en: 'The Most Huggable' },
  TitleData_Stargazer: { en: 'Stargazer' },
  TitleData_Striker: { en: 'The Eager Rookie' },
  TitleData_StudiestheBlade: { en: 'Studies the Blade' },
  TitleData_Summer_ExtremelyPunny: { en: 'Extremely Punny' },
  TitleData_Summer_HotandBothered: { en: 'Hot and Bothered' },
  TitleData_Summer_LifeoftheParty: { en: 'Life of the Party' },
  TitleData_Summer_OmegaSpiker: { en: 'Omega Spiker' },
  TitleData_Summer_OnDuty: { en: 'On Duty' },
  TitleData_Summer_SeaTier: { en: 'Sea Tier' },
  TitleData_Summer_SweetTreat: { en: 'Sweet Treat' },
  TitleData_SurfsUp: { en: 'Surf\'s Up!' },
  TitleData_TeamEDMOni: { en: 'Thousand Absolutes' },
  TitleData_TeamRockOni: { en: 'Vice Versa' },
  TitleData_TeaTime_Boba: { en: 'Boba' },
  TitleData_TeaTime_Caffeinated: { en: 'Caffeinated' },
  TitleData_TeaTime_Jelly: { en: 'Jelly' },
  TitleData_TempoSniperMastery: { en: 'Fashion Icon' },
  TitleData_TheChampion: { en: 'The Champion' },
  TitleData_TheDirector: { en: 'The Director' },
  TitleData_TheGlizzard: { en: 'The Glizzard' },
  TitleData_TheGoldenStandard: { en: 'The Golden Standard' },
  TitleData_TheNextBigThing: { en: 'The Next Big Thing' },
  TitleData_TheProphet: { en: 'The Prophet' },
  TitleData_TheShepherd: { en: 'The Shepherd' },
  TitleData_TournamentShadowHelper: { en: 'Shadow Helper' },
  TitleData_TournamentShadowHero: { en: 'Shadow Hero' },
  TitleData_TournamentShadowLoser: { en: 'World\'s Best Loser' },
  TitleData_TournamentShadowSelfless: { en: 'The Selfless' },
  TitleData_TournamentShadowWarrior: { en: 'Shadow Warrior' },
  TitleData_Trailblazer: { en: 'Trailblazer' },
  TitleData_UmbrellaUserMastery: { en: 'Loose Cannon' },
  TitleData_WatchingTheSunset: { en: 'Watching The Sunset' },
  TitleData_WestieRoyalty: { en: 'Westie Royalty' },
  TitleData_Whatdayisit: { en: 'What day is it?' },
  TitleData_WhipFighterMastery: { en: 'Off the Hook' },
}
