export const TitleLookup = {
  TitleData_Abandoned: { en: 'Abandoned' },
  TitleData_Aesop: { en: 'Aesop' },
  TitleData_AngelicSupportMastery: { en: 'Time Traveler' },
  TitleData_BetaReward: { en: 'The Eternal Flame' },
  TitleData_BPS1Investor: { en: 'The Early Investor' },
  TitleData_BPS1Striker: { en: 'Beta Season Striker' },
  TitleData_BPS2Hotshot: { en: 'The Hotshot' },
  TitleData_BPS2Striker: { en: 'Season Two Striker' },
  TitleData_BuiltDifferent: { en: 'Built Different' },
  TitleData_ChaoticRocketeerMastery: { en: 'Chaotic' },
  TitleData_CleverSummonerMastery: { en: 'Blobbo Buddy' },
  TitleData_Competitor: { en: 'Competitor' },
  TitleData_Cracked: { en: 'Cracked' },
  TitleData_Cringe: { en: 'Cringe' },
  TitleData_EDMOniMastery: { en: 'Virtuoso' },
  TitleData_EmpoweringEnchanterMastery: { en: 'Bewitched' },
  TitleData_FlashySwordsmanMastery: { en: 'Blade Master' },
  TitleData_FlexibleBrawlerMastery: { en: 'Rising Star' },
  TitleData_Founder: { en: 'Founding Member' },
  TitleData_GravityMageMastery: { en: 'Illusionist' },
  TitleData_Halloween_Pumpkin: { en: 'Pumpkin' },
  TitleData_Halloween_Spooky: { en: 'Spooky' },
  TitleData_HulkingBeastMastery: { en: 'Excessive' },
  TitleData_HyperX: { en: 'HyperX Hero' },
  TitleData_Idol: { en: 'Idol' },
  TitleData_KOChamp: { en: 'K.O. Champ' },
  TitleData_MagicalPlaymakerMastery: { en: 'Glitchy' },
  TitleData_ManipulatingMastermindMastery: { en: 'Sinister Shadow' },
  TitleData_MasterBrawler: { en: 'Expert Brawler' },
  TitleData_MasterSniper: { en: 'Expert Sniper' },
  TitleData_NimbleBlasterMastery: { en: 'Space Invader' },
  TitleData_None: { en: 'No title :(' },
  TitleData_Performer: { en: 'Performer' },
  TitleData_RiseandGrind: { en: 'Rise & Grind' },
  TitleData_RockOniMastery: { en: 'Rock Star' },
  TitleData_S1Champion: { en: 'Beta Season Omega Striker' },
  TitleData_S1TournamentChampion: { en: 'S1 Tournament Champion' },
  TitleData_S1TournamentFlawless: { en: 'S1 Flawless Tournament Winner' },
  TitleData_S1TournamentLegend: { en: 'S1 Tournament Legend' },
  TitleData_S1TournamentWarrior: { en: 'S1 Tournament Warrior' },
  TitleData_S1TournamentWinner: { en: 'S1 Tournament Winner' },
  TitleData_ScalingForLateGame: { en: 'Scaling For Late Game' },
  TitleData_ShieldUserMastery: { en: 'Unbreakable' },
  TitleData_SigmaStriker: { en: 'Sigma Striker' },
  TitleData_SpeedySkirmisherMastery: { en: 'Prodigy' },
  TitleData_StalwartProtectorMastery: { en: 'The Most Huggable' },
  TitleData_Striker: { en: 'The Eager Rookie' },
  TitleData_TeamEDMOni: { en: 'Thousand Absolutes' },
  TitleData_TeamRockOni: { en: 'Vice Versa' },
  TitleData_TeaTime_Boba: { en: 'Boba' },
  TitleData_TeaTime_Caffeinated: { en: 'Caffeinated' },
  TitleData_TeaTime_Jelly: { en: 'Jelly' },
  TitleData_TempoSniperMastery: { en: 'Fashion Icon' },
  TitleData_TournamentShadowHelper: { en: 'Shadow Helper' },
  TitleData_TournamentShadowHero: { en: 'Shadow Hero' },
  TitleData_TournamentShadowLoser: { en: 'World\'s Best Loser' },
  TitleData_TournamentShadowSelfless: { en: 'The Selfless' },
  TitleData_TournamentShadowWarrior: { en: 'Shadow Warrior' },
  TitleData_Trailblazer: { en: 'Trailblazer' },
  TitleData_WhipFighterMastery: { en: 'Off the Hook' },
}